# pull official base image
FROM rust:latest

# set work directory
WORKDIR /app

# copy project
COPY . .

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# RUN cargo install --path .

# install dependencies
RUN apt-get update && apt-get install -y build-essential git && apt-get -y install gcc \
  && apt-get install -y libssl-dev libffi-dev musl-dev \
  && apt-get install python3-dev pip -y


RUN pip install --upgrade pip



COPY requirements.txt .
RUN pip install -r requirements.txt
