# pull official base image
FROM huggingface/transformers-pytorch-gpu:latest

# set work directory
WORKDIR /app

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


COPY requirements.txt .
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
RUN pip install -r requirements.txt

RUN pip list

# copy project
COPY . .

###############
# NOTE: comment out transformer & pytorch from requirements.txt
################