"""Change order and book model

Revision ID: 15358e5829b8
Revises: 00ca02d1eeee
Create Date: 2021-12-10 11:49:43.852147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15358e5829b8'
down_revision = '00ca02d1eeee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_name', sa.String(length=10), nullable=False))
    op.add_column('orders', sa.Column('post_code', sa.String(length=10), nullable=False))
    op.alter_column('orders', 'name',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'name',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('orders', 'post_code')
    op.drop_column('orders', 'delivery_name')
    # ### end Alembic commands ###
