"""add delivery memo

Revision ID: bbce0178d9e0
Revises: 15358e5829b8
Create Date: 2021-12-12 17:55:51.666547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbce0178d9e0'
down_revision = '15358e5829b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_memo', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_memo')
    # ### end Alembic commands ###
