// db 주소 관련 수정 필요
conn = new Mongo();
db = db.getSiblingDB("flower_letter_db");

db.createCollection("flowers");

//  Insert Documnets
db.flowers.insertMany([
  {
    flower: "가막살나무",
    symbol: "죽음보다 강한 사랑",
    image_url: "red",
    keywords: ["사랑"],
  },
  {
    flower: "가문비나무",
    symbol: "성실, 정직",
    image_url: "pink",
    keywords: ["생각", "희망"],
  },
  {
    flower: "가시박",
    symbol: "기다림",
    image_url: "yellow",
    keywords: ["생각", "시간"],
  },
  { flower: "가지", symbol: "진실", image_url: "blue", keywords: ["희망"] },
  {
    flower: "각시투구꽃",
    symbol: "용사의 모자",
    image_url: "purple",
    keywords: ["희망"],
  },
  {
    flower: "갈대",
    symbol: "신의, 믿음, 지혜",
    image_url: "white",
    keywords: ["희망"],
  },
  {
    flower: "감나무",
    symbol: "경의, 자애, 소박",
    image_url: "red",
    keywords: ["희망"],
  },
  {
    flower: "감자",
    symbol: "당신을 따르겠습니다",
    image_url: "pink",
    keywords: ["사랑"],
  },
  { flower: "갓", symbol: "무관심", image_url: "yellow", keywords: ["생각"] },
  {
    flower: "강아지풀",
    symbol: "동심, 노여움",
    image_url: "blue",
    keywords: ["시간", "분노"],
  },
  {
    flower: "개나리",
    symbol: "희망, 나의 사랑은 당신보다 깊습니다",
    image_url: "purple",
    keywords: ["사랑"],
  },
  {
    flower: "개불알꽃(= 복주머니란)",
    symbol: "나를 이겨 가지세요.",
    image_url: "white",
    keywords: ["희망", "사랑"],
  },
  { flower: "개별꽃", symbol: "귀여움", image_url: "red", keywords: ["사랑"] },
  {
    flower: "개다래나무",
    symbol: "꿈꾸는 심정",
    image_url: "pink",
    keywords: ["희망"],
  },
  { flower: "개망초", symbol: "화해", image_url: "yellow", keywords: ["희망"] },
  {
    flower: "개미취",
    symbol: "기억, 추억, 먼 곳의 벗을 그리워하다",
    image_url: "blue",
    keywords: ["시간", "슬픔"],
  },
  {
    flower: "개벚지나무",
    symbol: "시골 처녀",
    image_url: "purple",
    keywords: ["생각", "자연", "희망"],
  },
  {
    flower: "개암나무",
    symbol: "화해, 잘 어울리는 한쌍",
    image_url: "white",
    keywords: ["희망"],
  },
  {
    flower: "개양귀비",
    symbol: "약한 사랑, 덧없는 사랑, 무관심, 냉담",
    image_url: "red",
    keywords: ["슬픔"],
  },
  {
    flower: "개회나무",
    symbol: "청춘의 추억",
    image_url: "pink",
    keywords: ["시간"],
  },
  {
    flower: "갯버들",
    symbol: "친절, 자유",
    image_url: "yellow",
    keywords: ["생각", "자연"],
  },
  {
    flower: "거베라",
    symbol: "신비, 풀 수 없는 수수께끼",
    image_url: "blue",
    keywords: ["생각", "문학"],
  },
  { flower: "겨자", symbol: "무관심", image_url: "purple", keywords: ["생각"] },
  {
    flower: "겨우살이",
    symbol: "강한 인내심",
    image_url: "white",
    keywords: ["생각"],
  },
  {
    flower: "계요등",
    symbol: "지혜",
    image_url: "red",
    keywords: ["생각", "희망"],
  },
  {
    flower: "고광나무",
    symbol: "기품, 품격, 추억",
    image_url: "pink",
    keywords: ["시간", "희망"],
  },
  {
    flower: "고데마리",
    symbol: "노력",
    image_url: "yellow",
    keywords: ["생각"],
  },
  {
    flower: "고무나무",
    symbol: "변함 없는 사랑, 영원한 행복",
    image_url: "blue",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "고사리",
    symbol: "기적, 유혹",
    image_url: "purple",
    keywords: ["감각", "희망"],
  },
  {
    flower: "고추나무",
    symbol: "한, 의혹, 미신",
    image_url: "white",
    keywords: ["생각", "슬픔"],
  },
  { flower: "고추나물", symbol: "친절", image_url: "red", keywords: ["희망"] },
  {
    flower: "공작선인장",
    symbol: "정열",
    image_url: "pink",
    keywords: ["사랑"],
  },
  {
    flower: "괴불나무",
    symbol: "사랑의 희열",
    image_url: "yellow",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "공작초",
    symbol: "항상 좋은 기분, 안부",
    image_url: "blue",
    keywords: ["감각", "희망"],
  },
  {
    flower: "과꽃",
    symbol: "믿는 사랑, 추억",
    image_url: "purple",
    keywords: ["시간", "사랑"],
  },
  { flower: "관음죽", symbol: "행운", image_url: "white", keywords: ["희망"] },
  {
    flower: "광나무",
    symbol: "강인한 마음",
    image_url: "red",
    keywords: ["생각", "감각", "희망"],
  },
  {
    flower: "구상나무",
    symbol: "기개",
    image_url: "pink",
    keywords: ["생각", "신체", "감각", "희망"],
  },
  {
    flower: "구즈베리아",
    symbol: "만족",
    image_url: "yellow",
    keywords: ["감각", "희망"],
  },
  {
    flower: "구름패랭이꽃",
    symbol: "위급",
    image_url: "blue",
    keywords: ["공포"],
  },
  {
    flower: "구골나무",
    symbol: "보호, 용의",
    image_url: "purple",
    keywords: ["공포"],
  },
  {
    flower: "국화",
    symbol: "정말 좋은 친구",
    image_url: "white",
    keywords: ["가족", "희망"],
  },
  {
    flower: "국화 (하얀 국화)",
    symbol: "성실, 진실",
    image_url: "white",
    keywords: ["생각", "희망"],
  },
  {
    flower: "국화 (노란 국화)",
    symbol: "실망, 짝사랑",
    image_url: "yellow",
    keywords: ["사랑", "슬픔"],
  },
  {
    flower: "국화 (빨간 국화)",
    symbol: "진실",
    image_url: "red",
    keywords: ["생각"],
  },
  {
    flower: "국수나무",
    symbol: "모정",
    image_url: "red",
    keywords: ["가족", "희망"],
  },
  {
    flower: "군자란",
    symbol: "고귀",
    image_url: "pink",
    keywords: ["생각", "희망"],
  },
  {
    flower: "굴거리나무",
    symbol: "내 사랑 나의 품에",
    image_url: "yellow",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "구기자나무",
    symbol: "희생",
    image_url: "blue",
    keywords: ["생각", "죽음", "신체", "희망", "슬픔"],
  },
  {
    flower: "궁궁이",
    symbol: "고결",
    image_url: "purple",
    keywords: ["생각", "감각", "희망"],
  },
  {
    flower: "귀룽나무",
    symbol: "사색",
    image_url: "white",
    keywords: ["생각"],
  },
  { flower: "귤", symbol: "마음의 스승", image_url: "red", keywords: ["생각"] },
  {
    flower: "극락조화",
    symbol: "사랑을 위해 멋을 부린 남자, 신비, 영구불멸",
    image_url: "pink",
    keywords: ["시간", "문학", "사랑"],
  },
  {
    flower: "글라디올라스",
    symbol: "밀회, 경계, 주의",
    image_url: "yellow",
    keywords: ["감각", "사랑", "공포"],
  },
  {
    flower: "글로리오사",
    symbol: "광영, 영광",
    image_url: "blue",
    keywords: ["시간", "슬픔"],
  },
  {
    flower: "글록시니아",
    symbol: "화려한 모습, 욕망",
    image_url: "purple",
    keywords: ["생각", "감각"],
  },
  {
    flower: "금관화",
    symbol: "화려한 추억",
    image_url: "white",
    keywords: ["시간", "감각"],
  },
  {
    flower: "금괭이눈",
    symbol: "골짜기의 황금, 변하기 쉬운 마음",
    image_url: "red",
    keywords: ["생각", "문학", "슬픔"],
  },
  {
    flower: "금귤",
    symbol: "순결, 어릴 때 우정",
    image_url: "pink",
    keywords: ["생각", "시간", "감각"],
  },
  {
    flower: "금낭화",
    symbol: "당신을 따르겠습니다.",
    image_url: "yellow",
    keywords: ["생각", "희망", "사랑"],
  },
  {
    flower: "금매화",
    symbol: "꿈 많은 소녀",
    image_url: "blue",
    keywords: ["문학"],
  },
  {
    flower: "금목서",
    symbol: "당신의 마음을 끌다.",
    image_url: "purple",
    keywords: ["생각", "사랑"],
  },
  {
    flower: "금사슬나무",
    symbol: "슬픈 아름다움",
    image_url: "white",
    keywords: ["생각", "문학", "감각", "사랑", "슬픔"],
  },
  {
    flower: "금어초",
    symbol: "수다쟁이, 주제넘게 참견하다",
    image_url: "red",
    keywords: ["문학", "분노"],
  },
  {
    flower: "금영화",
    symbol: "희망, 부, 성공",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "금잔화",
    symbol: "비탄, 실망, 비애, 겸손, 인내, 이별의 슬픔",
    image_url: "yellow",
    keywords: ["슬픔"],
  },
  {
    flower: "금작화",
    symbol: "청초",
    image_url: "blue",
    keywords: ["신체", "감각", "희망"],
  },
  {
    flower: "기린초",
    symbol: "소녀의 사랑",
    image_url: "purple",
    keywords: ["문학", "사랑"],
  },
  { flower: "기생꽃", symbol: "천사", image_url: "white", keywords: ["문학"] },
  {
    flower: "긴개싱아",
    symbol: "백로다리",
    image_url: "red",
    keywords: ["문학", "공간"],
  },
  {
    flower: "까치밥나무",
    symbol: "풍요, 숨겨진 사랑",
    image_url: "pink",
    keywords: ["감각", "사랑"],
  },
  {
    flower: "꽃사과",
    symbol: "유혹",
    image_url: "red",
    keywords: ["생각", "감각", "사랑"],
  },
  { flower: "꽃다지", symbol: "무관심", image_url: "pink", keywords: ["생각"] },
  {
    flower: "꽃생강",
    symbol: "신뢰, 헛수고",
    image_url: "yellow",
    keywords: ["슬픔"],
  },
  {
    flower: "꽃잔디",
    symbol: "희생",
    image_url: "blue",
    keywords: ["생각", "죽음", "슬픔"],
  },
  {
    flower: "꽃쥐손이",
    symbol: "새색시",
    image_url: "purple",
    keywords: ["가족"],
  },
  {
    flower: "꽃창포",
    symbol: "우아한 마음, 좋은 소식",
    image_url: "white",
    keywords: ["생각", "희망"],
  },
  {
    flower: "꽃향유",
    symbol: "가을향기, 과거를 묻지 마세요",
    image_url: "red",
    keywords: ["자연", "시간", "감각"],
  },
  {
    flower: "꽈리",
    symbol: "거짓, 속임수",
    image_url: "pink",
    keywords: ["생각", "분노"],
  },
  {
    flower: "꽝꽝나무",
    symbol: "참고 견디어 낼 줄 아는",
    image_url: "yellow",
    keywords: ["생각", "신체", "감각"],
  },
  {
    flower: "그레빌레아 로부티스타",
    symbol: "가련",
    image_url: "blue",
    keywords: ["생각", "슬픔", "공포"],
  },
  {
    flower: "그로키니시아",
    symbol: "야심, 욕심",
    image_url: "purple",
    keywords: ["생각", "신체"],
  },
  {
    flower: "나팔꽃",
    symbol: "기쁨, 결속, 덧없는 사랑, 일편단심 사랑",
    image_url: "white",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "나도밤나무",
    symbol: "나를 업신여기지 마세요",
    image_url: "red",
    keywords: ["분노"],
  },
  {
    flower: "나비콩",
    symbol: "매력, 매혹",
    image_url: "pink",
    keywords: ["사랑"],
  },
  {
    flower: "난초",
    symbol: "청초한 아름다움, 열렬하고도 순수한 사랑",
    image_url: "yellow",
    keywords: ["문학", "감각", "사랑"],
  },
  {
    flower: "남천",
    symbol: "전화위복",
    image_url: "blue",
    keywords: ["문학", "희망", "슬픔"],
  },
  {
    flower: "납매",
    symbol: "자애",
    image_url: "purple",
    keywords: ["가족", "사랑"],
  },
  {
    flower: "냉이",
    symbol: "나의 모든 것을 당신에게 바칩니다",
    image_url: "white",
    keywords: ["생각", "신체", "희망", "사랑"],
  },
  {
    flower: "너도밤나무",
    symbol: "번영",
    image_url: "red",
    keywords: ["시간", "신체", "희망"],
  },
  {
    flower: "넌출월귤",
    symbol: "마음의 고통을 위로하다",
    image_url: "pink",
    keywords: ["죽음", "감각", "사랑", "슬픔"],
  },
  {
    flower: "네모필라",
    symbol: "애국심",
    image_url: "yellow",
    keywords: ["생각", "공간"],
  },
  {
    flower: "네프로네피스",
    symbol: "매혹",
    image_url: "blue",
    keywords: ["감각", "사랑"],
  },
  {
    flower: "노각나무",
    symbol: "견고, 정의",
    image_url: "purple",
    keywords: ["생각", "희망"],
  },
  {
    flower: "노간주나무",
    symbol: "친절, 자유",
    image_url: "white",
    keywords: ["희망"],
  },
  {
    flower: "노란별수선",
    symbol: "빛을 찾다",
    image_url: "red",
    keywords: ["자연", "문학"],
  },
  {
    flower: "노루귀",
    symbol: "인내, 믿음, 신뢰",
    image_url: "pink",
    keywords: ["생각", "희망", "공포"],
  },
  {
    flower: "노린재나무",
    symbol: "동의",
    image_url: "red",
    keywords: ["생각", "희망"],
  },
  {
    flower: "노송나무",
    symbol: "불명, 불사, 굳셈",
    image_url: "pink",
    keywords: ["시간", "신체", "문학", "희망"],
  },
  {
    flower: "누리장나무",
    symbol: "친애, 깨끗한 사랑",
    image_url: "yellow",
    keywords: ["생각", "자연", "희망", "사랑"],
  },
  {
    flower: "뉴사이란",
    symbol: "참신",
    image_url: "blue",
    keywords: ["생각", "시간", "감각"],
  },
  {
    flower: "느릅나무",
    symbol: "위엄",
    image_url: "purple",
    keywords: ["문학", "감각"],
  },
  {
    flower: "느티나무",
    symbol: "운명",
    image_url: "white",
    keywords: ["시간", "문학"],
  },
  {
    flower: "능금나무",
    symbol: "은화, 참애호자",
    image_url: "red",
    keywords: ["도시"],
  },
  {
    flower: "능소화",
    symbol: "여성, 명예, 영광, 기다림, 그리움",
    image_url: "pink",
    keywords: ["사랑", "슬픔"],
  },
  {
    flower: "뉴사이란",
    symbol: "참신하다",
    image_url: "yellow",
    keywords: ["생각"],
  },
  {
    flower: "니겔라",
    symbol: "꿈속의 사랑, 당혹, 미래, 은근한 기쁨",
    image_url: "blue",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "다릅나무",
    symbol: "선한",
    image_url: "purple",
    keywords: ["자연", "희망"],
  },
  {
    flower: "다정큼나무",
    symbol: "친밀",
    image_url: "white",
    keywords: ["가족", "감각", "사랑"],
  },
  {
    flower: "단정화",
    symbol: "당신을 버리지 않겠습니다",
    image_url: "red",
    keywords: ["생각", "문학", "희망", "공포"],
  },
  {
    flower: "단풍나무",
    symbol: "사양",
    image_url: "pink",
    keywords: ["생각", "분노"],
  },
  {
    flower: "달리아",
    symbol: "정열, 불안정, 변덕",
    image_url: "yellow",
    keywords: ["사랑", "분노"],
  },
  {
    flower: "달맞이꽃",
    symbol: "말 없는 사랑, 기다림, 밤의 요정, 소원, 마법, 마력",
    image_url: "blue",
    keywords: ["시간", "문학", "사랑"],
  },
  {
    flower: "달꽃",
    symbol: "꿈꾸는 사랑",
    image_url: "purple",
    keywords: ["생각", "문학", "사랑"],
  },
  {
    flower: "담자리꽃나무",
    symbol: "사랑에 눈 떼지 마!",
    image_url: "white",
    keywords: ["감각", "사랑"],
  },
  {
    flower: "담배",
    symbol: "기분",
    image_url: "red",
    keywords: ["생각", "감각"],
  },
  {
    flower: "담쟁이덩굴",
    symbol: "아름다운 매력",
    image_url: "pink",
    keywords: ["감각", "사랑"],
  },
  {
    flower: "당근",
    symbol: "죽음도 아깝지 않으리",
    image_url: "yellow",
    keywords: ["생각", "죽음", "문학", "사랑"],
  },
  {
    flower: "당아욱",
    symbol: "자애, 어머니의 사랑",
    image_url: "blue",
    keywords: ["생각", "가족", "사랑"],
  },
  { flower: "당종려", symbol: "승리", image_url: "purple", keywords: ["희망"] },
  {
    flower: "대나무",
    symbol: "지조, 인내, 절개",
    image_url: "white",
    keywords: ["문학", "희망", "공포"],
  },
  {
    flower: "대왕송",
    symbol: "부귀",
    image_url: "red",
    keywords: ["감각", "공간", "희망"],
  },
  {
    flower: "대추나무",
    symbol: "처음 만남",
    image_url: "pink",
    keywords: ["생각"],
  },
  {
    flower: "댕강나무, 꽃댕강나무",
    symbol: "환영, 평안",
    image_url: "red",
    keywords: ["감각", "희망"],
  },
  {
    flower: "댕댕이덩굴",
    symbol: "적선",
    image_url: "red",
    keywords: ["생각", "감각"],
  },
  {
    flower: "더덕",
    symbol: "성실, 감사",
    image_url: "pink",
    keywords: ["생각", "희망"],
  },
  {
    flower: "덧나무",
    symbol: "용기",
    image_url: "yellow",
    keywords: ["희망", "공포"],
  },
  {
    flower: "덜꿩나무",
    symbol: "주저",
    image_url: "blue",
    keywords: ["생각", "공포"],
  },
  {
    flower: "데이지",
    symbol: "겸손과 아름다움, 천진난만함",
    image_url: "purple",
    keywords: ["신체", "감각", "희망"],
  },
  {
    flower: "블루데이지",
    symbol: "청아한 당신",
    image_url: "white",
    keywords: ["생각", "문학", "사랑"],
  },
  {
    flower: "샤스타데이지",
    symbol: "만사는 인내로부터, 순진, 평화",
    image_url: "red",
    keywords: ["생각", "문학", "희망"],
  },
  {
    flower: "리빙스턴데이지",
    symbol: "희망 , 평화 , 평등 , 인내, 겸손한 아름다움",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "덴드로비움",
    symbol: "자만심이 강한 미인, 말괄량이, 방자한 미인",
    image_url: "yellow",
    keywords: ["감각", "사랑", "분노"],
  },
  {
    flower: "덴파레",
    symbol: "매혹, 유능한",
    image_url: "blue",
    keywords: ["감각", "희망"],
  },
  {
    flower: "델피니움",
    symbol:
      "당신은 왜 나를 싫어합니까, 쉽게 변함, 경솔, 제 마음을 헤아려주세요",
    image_url: "purple",
    keywords: ["분노"],
  },
  {
    flower: "도꼬마리",
    symbol: "고집, 애교",
    image_url: "white",
    keywords: ["분노"],
  },
  {
    flower: "도라지꽃",
    symbol: "소망, 영원한 사랑",
    image_url: "purple",
    keywords: ["시간", "희망", "사랑"],
  },
  {
    flower: "동백꽃",
    symbol: "청렴, 절조, 그 누구보다 그대를 사랑합니다",
    image_url: "red",
    keywords: ["생각", "시간", "사랑"],
  },
  {
    flower: "동백꽃 (하얀 동백꽃)",
    symbol: "당신은 나의 사랑을 경멸하는 것입니까?",
    image_url: "white",
    keywords: ["사랑", "분노"],
  },
  {
    flower: "동백꽃 (붉은 동백꽃)",
    symbol: "나는 당신이 누구보다도 아름답다고 생각합니다.",
    image_url: "red",
    keywords: ["생각", "희망"],
  },
  {
    flower: "동백꽃 (복숭앗빛 동백꽃)",
    symbol: "나는 당신에게 사랑받는 것을 자랑으로 생각합니다.",
    image_url: "pink",
    keywords: ["생각", "사랑"],
  },
  {
    flower: "독당근",
    symbol: "죽음도 아깝지 않으리",
    image_url: "red",
    keywords: ["죽음"],
  },
  {
    flower: "독말풀",
    symbol: "거짓, 애교",
    image_url: "pink",
    keywords: ["분노"],
  },
  {
    flower: "독말풀 (하얀 독말풀)",
    symbol: "경애, 애증",
    image_url: "white",
    keywords: ["사랑", "분노"],
  },
  {
    flower: "독일창포",
    symbol: "멋진 결혼",
    image_url: "red",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "동심초",
    symbol: "온순",
    image_url: "pink",
    keywords: ["생각", "희망"],
  },
  {
    flower: "두릅나무",
    symbol: "애절, 희생",
    image_url: "yellow",
    keywords: ["죽음", "슬픔", "공포"],
  },
  {
    flower: "둥글레",
    symbol: "고귀한 봉사",
    image_url: "blue",
    keywords: ["생각", "문학", "감각", "희망"],
  },
  {
    flower: "들국화",
    symbol: "장애물, 상쾌",
    image_url: "yellow",
    keywords: ["희망", "분노"],
  },
  {
    flower: "들장미",
    symbol: "고독, 소박한 미, 시",
    image_url: "white",
    keywords: ["생각", "문학"],
  },
  {
    flower: "들쭉나무",
    symbol: "반항심",
    image_url: "red",
    keywords: ["생각", "분노"],
  },
  {
    flower: "등나무",
    symbol: "환영, 사랑에 취함",
    image_url: "pink",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "등골나무",
    symbol: "주저",
    image_url: "yellow",
    keywords: ["생각", "공포"],
  },
  {
    flower: "디기탈레스",
    symbol: "열애, 나는 애정을 숨길 수 없습니다",
    image_url: "blue",
    keywords: ["생각", "감각", "사랑"],
  },
  {
    flower: "딱총나무",
    symbol: "동정, 열심",
    image_url: "purple",
    keywords: ["생각", "사랑", "슬픔"],
  },
  {
    flower: "딸기",
    symbol: "예견, 행복한 가정, 존중, 애정, 우정, 우애",
    image_url: "white",
    keywords: ["생각", "가족", "희망", "사랑"],
  },
  {
    flower: "떡갈나무",
    symbol: "공명정대, 강건",
    image_url: "red",
    keywords: ["생각", "희망"],
  },
  { flower: "때죽나무", symbol: "겸손", image_url: "pink", keywords: ["생각"] },
  {
    flower: "뚜껑별꽃",
    symbol: "추억",
    image_url: "red",
    keywords: ["생각", "시간"],
  },
  {
    flower: "다알리아",
    symbol: "감사, 우아",
    image_url: "blue",
    keywords: ["생각"],
  },
  {
    flower: "다알리아 (하얀 다알리아)",
    symbol: "친절이 감사합니다",
    image_url: "white",
    keywords: ["생각", "희망"],
  },
  {
    flower: "다알리아 (장미색 다알리아)",
    symbol: "당신의 마음을 알게 되어 기쁩니다",
    image_url: "red",
    keywords: ["생각", "희망", "사랑"],
  },
  {
    flower: "다알리아 (빨간 다알리아)",
    symbol: "당신의 사랑이 나를 행복하게 합니다.",
    image_url: "red",
    keywords: ["문학", "희망", "사랑"],
  },
  {
    flower: "데코라고무나무",
    symbol: "남성적, 영원한 사랑",
    image_url: "purple",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "드라세나 드라코",
    symbol: "행복, 행운",
    image_url: "red",
    keywords: ["희망"],
  },
  {
    flower: "드라세나 산델리아나",
    symbol: "개운 (운이 열리다, 장수, 행운)",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "디모르 포세카",
    symbol: "해맑은 소녀, 회복",
    image_url: "yellow",
    keywords: ["신체", "희망"],
  },
  {
    flower: "디펜바키아",
    symbol: "경계",
    image_url: "blue",
    keywords: ["생각", "공포"],
  },
  {
    flower: "라그라스",
    symbol: "당신의 친절에 감사하다, 미안합니다",
    image_url: "purple",
    keywords: ["생각", "희망"],
  },
  {
    flower: "라넌큘러스",
    symbol: "매력, 매혹, 비난하다",
    image_url: "white",
    keywords: ["희망", "분노"],
  },
  {
    flower: "란타나",
    symbol: "엄격, 엄숙, 나는 변하지 않는다",
    image_url: "red",
    keywords: ["분노"],
  },
  {
    flower: "라벤더",
    symbol: "침묵, 정절, 내게 대답해주세요",
    image_url: "pink",
    keywords: ["생각", "신체"],
  },
  {
    flower: "라스피",
    symbol: "정의, 자유",
    image_url: "yellow",
    keywords: ["생각", "신체", "희망"],
  },
  {
    flower: "라임(린덴)",
    symbol: "부부간의 사랑",
    image_url: "blue",
    keywords: ["가족", "사랑"],
  },
  {
    flower: "라일락",
    symbol: "안녕, 첫사랑, 젊은 날의 추억",
    image_url: "purple",
    keywords: ["시간", "문학", "사랑"],
  },
  {
    flower: "라일락 (자주색 라일락)",
    symbol: "사랑의 싹이 트다",
    image_url: "purple",
    keywords: ["문학", "희망", "사랑"],
  },
  {
    flower: "라일락 (하얀 라일락)",
    symbol: "아름다운 맹세",
    image_url: "white",
    keywords: ["생각", "문학", "희망"],
  },
  {
    flower: "라일락 (빨간 라일락)",
    symbol: "친구의 사랑",
    image_url: "red",
    keywords: ["사랑"],
  },
  {
    flower: "라플레시아",
    symbol: "장대한 미와 순결",
    image_url: "red",
    keywords: ["자연", "신체", "문학", "공간", "사랑"],
  },
  {
    flower: "락스퍼",
    symbol: "정의, 자유",
    image_url: "purple",
    keywords: ["생각", "신체"],
  },
  {
    flower: "락스퍼 (보라 락스퍼)",
    symbol: "젊은 날의 추억",
    image_url: "purple",
    keywords: ["시간", "문학"],
  },
  {
    flower: "락스퍼 (빨간 락스퍼)",
    symbol: "사랑의 싹틈",
    image_url: "red",
    keywords: ["문학", "희망", "사랑"],
  },
  {
    flower: "레몬나무",
    symbol: "열의, 성실한 사랑, 정절",
    image_url: "yellow",
    keywords: ["생각", "신체", "사랑"],
  },
  {
    flower: "레몬",
    symbol: "진심으로 사모함",
    image_url: "yellow",
    keywords: ["생각", "사랑"],
  },
  {
    flower: "레몬그라스",
    symbol: "진심으로 사모함",
    image_url: "yellow",
    keywords: ["생각", "사랑"],
  },
  {
    flower: "레몬버베나",
    symbol: "인내, 조화",
    image_url: "yellow",
    keywords: ["생각", "자연", "신체", "희망", "공포"],
  },
  {
    flower: "레위시아",
    symbol: "천사의 눈물",
    image_url: "red",
    keywords: ["문학"],
  },
  {
    flower: "레제다오도라타",
    symbol: "매력",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "렉스베고니아",
    symbol: "부조화, 짝사랑",
    image_url: "yellow",
    keywords: ["문학", "사랑"],
  },
  { flower: "로단테", symbol: "영속", image_url: "blue", keywords: ["시간"] },
  {
    flower: "로벨리아",
    symbol: "불신, 정교, 원망, 악의, 위기의 시작",
    image_url: "purple",
    keywords: ["문학", "분노", "공포"],
  },
  {
    flower: "로사캠피온",
    symbol: "성실",
    image_url: "white",
    keywords: ["생각"],
  },
  {
    flower: "로즈마리",
    symbol:
      "기억, 영원한 사랑, 아름다운 추억, 나를 생각해요, 당신의 존재로 나를 소생시키다, 행복한 추억, 가정의 행복",
    image_url: "red",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "로즈힙",
    symbol: "무의식의 아름다움",
    image_url: "pink",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "루나리아",
    symbol: "정직",
    image_url: "yellow",
    keywords: ["생각", "희망"],
  },
  {
    flower: "루드베키아",
    symbol: "영원한 행복",
    image_url: "blue",
    keywords: ["시간", "희망"],
  },
  {
    flower: "루피너스",
    symbol: "모성애, 행복",
    image_url: "purple",
    keywords: ["가족", "희망"],
  },
  {
    flower: "리넘",
    symbol: "나는 당신의 친절에 감사합니다",
    image_url: "white",
    keywords: ["생각", "희망"],
  },
  {
    flower: "리시안셔스",
    symbol: "변치 않는 사랑",
    image_url: "red",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "리시키톤",
    symbol: "아름다운 추억",
    image_url: "pink",
    keywords: ["시간", "희망"],
  },
  {
    flower: "리아트리스",
    symbol: "고집쟁이, 고결, 기다림",
    image_url: "yellow",
    keywords: ["생각", "분노"],
  },
  {
    flower: "러브체인",
    symbol: "끈끈한 사랑",
    image_url: "blue",
    keywords: ["시간", "감각", "사랑"],
  },
  {
    flower: "로단테",
    symbol: "아름다움, 영원한 사랑, 행복",
    image_url: "purple",
    keywords: ["생각", "시간", "희망", "사랑"],
  },
  {
    flower: "로드킬 선인장",
    symbol: "장구, 승승장구",
    image_url: "white",
    keywords: ["희망"],
  },
  {
    flower: "로즈베리",
    symbol: "당신은 나를 일깨운다",
    image_url: "red",
    keywords: ["생각", "문학"],
  },
  {
    flower: "리기다 소나무",
    symbol: "희망의 속삭임",
    image_url: "red",
    keywords: ["희망"],
  },
  {
    flower: "마가렛",
    symbol: "자유, 마음 속에 사랑을 점친다",
    image_url: "pink",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "마로니에",
    symbol: "천분, 천재",
    image_url: "yellow",
    keywords: ["생각"],
  },
  { flower: "마르멜로", symbol: "유혹", image_url: "blue", keywords: ["사랑"] },
  {
    flower: "마취목",
    symbol: "희생",
    image_url: "purple",
    keywords: ["죽음", "신체", "슬픔"],
  },
  {
    flower: "마타리",
    symbol: "미인, 잴 수 없는 사랑",
    image_url: "white",
    keywords: ["사랑"],
  },
  {
    flower: "마시멜로",
    symbol: "은혜, 선행, 자선",
    image_url: "red",
    keywords: ["희망"],
  },
  {
    flower: "마조람",
    symbol: "조화, 기쁨, 행복",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "만병초",
    symbol: "위엄, 존엄, 경계, 위험",
    image_url: "yellow",
    keywords: ["공포"],
  },
  {
    flower: "만수국",
    symbol: "반드시 오고야 말 행복",
    image_url: "blue",
    keywords: ["희망"],
  },
  {
    flower: "망초",
    symbol:
      "화해, 가까이 있는 사람을 행복하게 해주고 멀리 있는 사람은 가까이 다가오게 해준다",
    image_url: "purple",
    keywords: ["문학"],
  },
  {
    flower: "만년청",
    symbol: "상속, 모성애",
    image_url: "white",
    keywords: ["생각", "가족", "사랑"],
  },
  {
    flower: "말채나무",
    symbol: "보호",
    image_url: "red",
    keywords: ["신체", "공포"],
  },
  {
    flower: "매자나무",
    symbol: "까다로움",
    image_url: "red",
    keywords: ["생각", "공포"],
  },
  {
    flower: "매화나무",
    symbol: "고결, 결백, 정조",
    image_url: "pink",
    keywords: ["생각"],
  },
  {
    flower: "맨드라미",
    symbol: "시들지 않는 사랑, 영생, 괴기",
    image_url: "yellow",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "메꽃",
    symbol: "속박, 충성, 수줍음",
    image_url: "red",
    keywords: ["생각", "문학"],
  },
  { flower: "메밀꽃", symbol: "연인", image_url: "pink", keywords: ["사랑"] },
  {
    flower: "매쉬메리골드",
    symbol: "반드시 오고야 말 행복",
    image_url: "yellow",
    keywords: ["희망"],
  },
  { flower: "머위", symbol: "공평", image_url: "blue", keywords: ["생각"] },
  {
    flower: "명자나무",
    symbol: "평범, 조숙, 겸손",
    image_url: "purple",
    keywords: ["생각"],
  },
  {
    flower: "모감주나무",
    symbol: "자유로운 마음, 기다림",
    image_url: "white",
    keywords: ["생각"],
  },
  {
    flower: "모란",
    symbol: "부귀, 영화, 왕자의 품격, 행복한 결혼",
    image_url: "red",
    keywords: ["문학", "희망", "사랑"],
  },
  {
    flower: "모링가",
    symbol: "생명의 나무",
    image_url: "pink",
    keywords: ["생각", "문학"],
  },
  {
    flower: "목련",
    symbol: "숭고한 정신, 우애, 고귀함",
    image_url: "yellow",
    keywords: ["생각", "감각"],
  },
  { flower: "목향", symbol: "인정", image_url: "blue", keywords: ["생각"] },
  {
    flower: "목화",
    symbol: "어머니의 사랑",
    image_url: "purple",
    keywords: ["가족", "사랑"],
  },
  {
    flower: "몬스테라",
    symbol: "괴기",
    image_url: "white",
    keywords: ["문학", "공포"],
  },
  { flower: "몰약나무", symbol: "진실", image_url: "red", keywords: ["생각"] },
  {
    flower: "무",
    symbol: "계절이 주는 풍요",
    image_url: "red",
    keywords: ["자연", "시간", "신체", "문학"],
  },
  {
    flower: "무궁화",
    symbol: "은근, 끈기, 섬세한 아름다움",
    image_url: "pink",
    keywords: ["신체", "문학"],
  },
  {
    flower: "무릇",
    symbol: "인내, 강한 자제력",
    image_url: "red",
    keywords: ["생각"],
  },
  {
    flower: "무스카리",
    symbol: "절망, 실의, 실망, 통하는 마음, 관대한 사랑",
    image_url: "pink",
    keywords: ["사랑", "슬픔"],
  },
  {
    flower: "무환자나무",
    symbol: "염원",
    image_url: "yellow",
    keywords: ["희망", "슬픔"],
  },
  {
    flower: "문주란",
    symbol: "청순함",
    image_url: "blue",
    keywords: ["문학", "희망"],
  },
  {
    flower: "물레나물",
    symbol: "일편단심, 추억",
    image_url: "purple",
    keywords: ["시간"],
  },
  {
    flower: "물망초",
    symbol: "나를 잊지 마세요, 진실한 사랑",
    image_url: "white",
    keywords: ["사랑"],
  },
  {
    flower: "물푸레나무",
    symbol: "열심",
    image_url: "red",
    keywords: ["생각"],
  },
  {
    flower: "미나리",
    symbol: "성의, 고결",
    image_url: "pink",
    keywords: ["생각"],
  },
  {
    flower: "미나리아재비",
    symbol: "천진난만함",
    image_url: "yellow",
    keywords: ["생각", "자연"],
  },
  {
    flower: "미니장미",
    symbol: "끝없는 사랑",
    image_url: "blue",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "미루나무",
    symbol: "명예, 영광",
    image_url: "purple",
    keywords: ["희망"],
  },
  {
    flower: "미모사",
    symbol: "민감, 섬세, 부끄러움",
    image_url: "white",
    keywords: ["감각"],
  },
  {
    flower: "미선나무",
    symbol: "모든 슬픔이 사라진다",
    image_url: "red",
    keywords: ["슬픔"],
  },
  {
    flower: "미스티블루",
    symbol: "청초한 사랑",
    image_url: "red",
    keywords: ["사랑"],
  },
  {
    flower: "매발톱나무",
    symbol: "승리의 맹세",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "민들레",
    symbol: "사랑의 사도, 행복, 불사신",
    image_url: "yellow",
    keywords: ["신체", "문학", "희망", "사랑"],
  },
  {
    flower: "민트",
    symbol: "다시 한 번 사랑하고 싶습니다, 미덕",
    image_url: "blue",
    keywords: ["문학", "사랑"],
  },
  { flower: "밀감", symbol: "친애", image_url: "purple", keywords: ["사랑"] },
  {
    flower: "밀집꽃",
    symbol: "항상 기억하라",
    image_url: "white",
    keywords: ["생각", "문학"],
  },
  {
    flower: "밀토니아",
    symbol: "슬픔은 없다",
    image_url: "red",
    keywords: ["문학", "희망"],
  },
  { flower: "무주나무", symbol: "자제", image_url: "pink", keywords: ["생각"] },
  {
    flower: "무화과",
    symbol: "결실있는 사랑",
    image_url: "yellow",
    keywords: ["사랑"],
  },
  {
    flower: "미니델피늄",
    symbol: "당신을 행복하게 해줄게요",
    image_url: "red",
    keywords: ["희망"],
  },
  {
    flower: "메도우 클라리 세이지",
    symbol: "구원, 존경, 건강, 미덕, 장수",
    image_url: "pink",
    keywords: ["문학", "희망"],
  },
  {
    flower: "말라코이데스 앵초",
    symbol: "부귀, 신비한 마음, 희망",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "말마비스쿠스",
    symbol: "미련, 아직도 다 못한 사랑",
    image_url: "blue",
    keywords: ["사랑", "슬픔"],
  },
  {
    flower: "멀티코옐로우",
    symbol: "평화, 희망",
    image_url: "purple",
    keywords: ["희망"],
  },
  {
    flower: "메타세쿼이아",
    symbol: "영원한 친구",
    image_url: "white",
    keywords: ["가족", "시간"],
  },
  {
    flower: "바비아나",
    symbol: "단란한 가족",
    image_url: "red",
    keywords: ["가족", "희망"],
  },
  {
    flower: "바질",
    symbol: "멋진 희망",
    image_url: "pink",
    keywords: ["감각", "희망"],
  },
  {
    flower: "바나나",
    symbol: "질투, 재능",
    image_url: "yellow",
    keywords: ["생각", "분노"],
  },
  {
    flower: "바디나물",
    symbol: "노여움, 동심",
    image_url: "blue",
    keywords: ["문학", "분노"],
  },
  {
    flower: "바이덴스",
    symbol: "황금의 여신",
    image_url: "purple",
    keywords: ["문학"],
  },
  {
    flower: "바카리스",
    symbol: "개척",
    image_url: "white",
    keywords: ["문학"],
  },
  { flower: "박달나무", symbol: "견고", image_url: "red", keywords: ["생각"] },
  {
    flower: "박쥐란",
    symbol: "교묘한, 괴이함",
    image_url: "red",
    keywords: ["공포"],
  },
  {
    flower: "박태기나무",
    symbol: "우정, 의혹, 형제애",
    image_url: "pink",
    keywords: ["가족"],
  },
  {
    flower: "박하",
    symbol: "미덕, 다시 한 번 사랑하고 싶습니다.",
    image_url: "yellow",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "반다",
    symbol: "애정의 표시",
    image_url: "blue",
    keywords: ["사랑"],
  },
  {
    flower: "밤나무",
    symbol: "포근한 사랑, 정의",
    image_url: "purple",
    keywords: ["사랑"],
  },
  {
    flower: "밤안개",
    symbol: "고운 마음",
    image_url: "white",
    keywords: ["생각"],
  },
  { flower: "방울꽃", symbol: "만족", image_url: "red", keywords: ["희망"] },
  { flower: "배꽃", symbol: "연모", image_url: "pink", keywords: ["사랑"] },
  {
    flower: "배롱나무",
    symbol: "부귀, 떠나간 친구에 대한 회상",
    image_url: "yellow",
    keywords: ["죽음", "문학"],
  },
  {
    flower: "배추꽃",
    symbol: "쾌활",
    image_url: "blue",
    keywords: ["신체", "희망"],
  },
  {
    flower: "백당나무",
    symbol: "마음",
    image_url: "purple",
    keywords: ["생각"],
  },
  {
    flower: "백목련",
    symbol: "이루어질 수 없는 사랑",
    image_url: "red",
    keywords: ["사랑", "슬픔"],
  },
  { flower: "백양나무", symbol: "시간", image_url: "pink", keywords: ["시간"] },
  {
    flower: "백일홍",
    symbol: "인연, 행복, 떠나간 님(혹은 친구)을 그리며",
    image_url: "red",
    keywords: ["생각", "죽음", "희망", "사랑"],
  },
  {
    flower: "백합",
    symbol: "순결, 순수한 사랑, 깨끗한 사랑, 변함없는 사랑, 죽음",
    image_url: "blue",
    keywords: ["신체", "문학", "사랑"],
  },
  {
    flower: "버드나무",
    symbol: "태평세월, 자유",
    image_url: "purple",
    keywords: ["자연"],
  },
  { flower: "버베나", symbol: "단결", image_url: "white", keywords: ["생각"] },
  { flower: "버섯", symbol: "유혹", image_url: "red", keywords: ["생각"] },
  {
    flower: "벌개미취",
    symbol: "너를 잊지 않으리",
    image_url: "pink",
    keywords: ["생각", "슬픔"],
  },
  {
    flower: "범의귀",
    symbol: "전 당신을 기쁘게 해주겠습니다, 당신에게 미움받는 다면 죽겠습니다",
    image_url: "yellow",
    keywords: ["문학"],
  },
  {
    flower: "벚꽃",
    symbol:
      "아름다운 정신(영혼), 정신적 사랑, 삶의 아름다움과 덧없음, 절세미인, 가장 아름다운 순간",
    image_url: "pink",
    keywords: ["사랑"],
  },
  {
    flower: "벽오동",
    symbol: "사모, 그리움",
    image_url: "pink",
    keywords: ["슬픔"],
  },
  { flower: "별꽃", symbol: "환영", image_url: "yellow", keywords: ["희망"] },
  {
    flower: "병꽃나무",
    symbol: "전설",
    image_url: "blue",
    keywords: ["생각", "문학"],
  },
  {
    flower: "베고니아",
    symbol: "정중, 친절, 짝사랑",
    image_url: "purple",
    keywords: ["사랑"],
  },
  {
    flower: "베르가못",
    symbol: "풍부한 감수성",
    image_url: "white",
    keywords: ["문학"],
  },
  {
    flower: "보리",
    symbol: "번영, 보편",
    image_url: "red",
    keywords: ["희망"],
  },
  {
    flower: "보리수",
    symbol: "결혼, 부부의 사랑",
    image_url: "pink",
    keywords: ["가족", "사랑"],
  },
  { flower: "보리지", symbol: "용기", image_url: "yellow", keywords: ["생각"] },
  {
    flower: "복사꽃",
    symbol: "매력, 유혹, 용서, 희망",
    image_url: "blue",
    keywords: ["희망"],
  },
  {
    flower: "복자기나무",
    symbol: "약속",
    image_url: "purple",
    keywords: ["생각"],
  },
  {
    flower: "봄맞이꽃",
    symbol: "봄맞이",
    image_url: "white",
    keywords: ["자연", "시간", "문학"],
  },
  {
    flower: "봉선화",
    symbol: "부귀, 여린 아이같은 마음씨, 아이같은 마음씨, 나를 건드리지 마세요",
    image_url: "red",
    keywords: ["문학", "희망", "공포"],
  },
  {
    flower: "부바르디아",
    symbol: "당신의 포로가 되었습니다",
    image_url: "pink",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "부용",
    symbol: "섬세한 아름다움",
    image_url: "yellow",
    keywords: ["문학", "감각"],
  },
  {
    flower: "부추",
    symbol: "무한한 슬픔, 별에 소원",
    image_url: "blue",
    keywords: ["시간", "슬픔"],
  },
  {
    flower: "분꽃",
    symbol: "수줍음, 소심, 겁쟁이",
    image_url: "purple",
    keywords: ["희망"],
  },
  {
    flower: "분꽃나무",
    symbol: "수줍음",
    image_url: "white",
    keywords: ["희망"],
  },
  {
    flower: "붓꽃",
    symbol: "기쁜 소식, 잘 전해 주세요, 사랑의 메시지",
    image_url: "purple",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "분단나무",
    symbol: "사람의 마음",
    image_url: "red",
    keywords: ["생각"],
  },
  {
    flower: "블루베리",
    symbol: "현명, 친절",
    image_url: "blue",
    keywords: ["생각"],
  },
  {
    flower: "비자나무",
    symbol: "소중, 사랑스러운 미소",
    image_url: "yellow",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "빈카",
    symbol: "우정, 즐거운 추억, 당신을 사랑합니다",
    image_url: "red",
    keywords: ["시간", "사랑"],
  },
  { flower: "비파", symbol: "현명", image_url: "pink", keywords: ["생각"] },
  {
    flower: "빌베르기아",
    symbol: "만족",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "보로니아",
    symbol: "여인의 향기",
    image_url: "blue",
    keywords: ["문학"],
  },
  {
    flower: "뻐꾹나리",
    symbol: "당당",
    image_url: "purple",
    keywords: ["생각"],
  },
  {
    flower: "뽕나무",
    symbol: "지혜, 못 이룬 사랑, 봉사",
    image_url: "white",
    keywords: ["생각", "사랑"],
  },
  {
    flower: "반디지치",
    symbol: "희생",
    image_url: "red",
    keywords: ["죽음", "슬픔"],
  },
  {
    flower: "방크스 소나무",
    symbol: "희망의 속삭임",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "방크시아",
    symbol: "이루어질 수 없는 사랑",
    image_url: "yellow",
    keywords: ["사랑"],
  },
  {
    flower: "벨로페로네",
    symbol: "겸손, 청초",
    image_url: "blue",
    keywords: ["생각"],
  },
  {
    flower: "부겐빌레아",
    symbol: "정열, 조화",
    image_url: "purple",
    keywords: ["희망"],
  },
  {
    flower: "뷰글라스",
    symbol: "진실",
    image_url: "white",
    keywords: ["생각"],
  },
  {
    flower: "브라질아브틸론",
    symbol: "당신을 따르겠습니다",
    image_url: "red",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "브리오니아",
    symbol: "거절",
    image_url: "pink",
    keywords: ["생각", "분노"],
  },
  {
    flower: "사루비아",
    symbol: "불타는 마음, 정열, 가족애",
    image_url: "yellow",
    keywords: ["가족", "사랑"],
  },
  {
    flower: "사과나무",
    symbol: "명예, 영광, 현명, 성공",
    image_url: "blue",
    keywords: ["희망"],
  },
  {
    flower: "사라세니아",
    symbol: "끈기",
    image_url: "purple",
    keywords: ["생각"],
  },
  {
    flower: "사상크로스",
    symbol: "그리움, 애교",
    image_url: "white",
    keywords: ["신체", "슬픔"],
  },
  {
    flower: "사랑초",
    symbol: "당신을 버리지 않겠습니다",
    image_url: "red",
    keywords: ["생각", "문학", "사랑"],
  },
  {
    flower: "사보렌",
    symbol: "온정, 열정, 존경",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "사상자",
    symbol: "순결, 결백",
    image_url: "yellow",
    keywords: ["생각", "신체"],
  },
  {
    flower: "사스레피나무",
    symbol: "당신은 소중합니다",
    image_url: "red",
    keywords: ["생각", "문학", "사랑"],
  },
  {
    flower: "사프란",
    symbol: "환희, 지나간 행복, 절제의 미",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "사철나무",
    symbol: "변화 없음",
    image_url: "yellow",
    keywords: ["시간"],
  },
  { flower: "산나리", symbol: "순결", image_url: "blue", keywords: ["생각"] },
  {
    flower: "산당화",
    symbol: "겸손, 단조",
    image_url: "purple",
    keywords: ["생각"],
  },
  {
    flower: "산딸기",
    symbol: "사랑, 마음 아픈 열애",
    image_url: "white",
    keywords: ["사랑", "슬픔"],
  },
  {
    flower: "산사나무",
    symbol: "유일한 사랑",
    image_url: "red",
    keywords: ["생각", "사랑"],
  },
  {
    flower: "산세베리아",
    symbol: "관용, 약속을 실행하다",
    image_url: "pink",
    keywords: ["생각", "문학"],
  },
  {
    flower: "산하엽",
    symbol: "친애의 정, 행복, 청초한 사람",
    image_url: "yellow",
    keywords: ["희망"],
  },
  { flower: "산황나무", symbol: "발전", image_url: "blue", keywords: ["생각"] },
  {
    flower: "산세베리아",
    symbol: "관용",
    image_url: "purple",
    keywords: ["생각"],
  },
  {
    flower: "산수유",
    symbol: "지속, 불변",
    image_url: "white",
    keywords: ["생각", "시간"],
  },
  {
    flower: "산앵두",
    symbol: "오로지 한 사랑",
    image_url: "red",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "산옥잠화",
    symbol: "망각의 사랑",
    image_url: "pink",
    keywords: ["시간", "사랑", "슬픔"],
  },
  {
    flower: "살구나무",
    symbol: "아가씨의 수줍음",
    image_url: "pink",
    keywords: ["문학"],
  },
  {
    flower: "삼나무",
    symbol: "웅대, 그대를 위해 살다",
    image_url: "blue",
    keywords: ["문학"],
  },
  {
    flower: "상사화",
    symbol: "이룰 수 없는 행복(사랑)",
    image_url: "purple",
    keywords: ["문학", "사랑", "슬픔"],
  },
  {
    flower: "상수리나무",
    symbol: "번영",
    image_url: "red",
    keywords: ["희망"],
  },
  {
    flower: "색동호박",
    symbol: "나의 마음은 아름답다",
    image_url: "pink",
    keywords: ["문학"],
  },
  {
    flower: "생달나무",
    symbol: "위로",
    image_url: "yellow",
    keywords: ["생각", "슬픔"],
  },
  {
    flower: "샌달우드",
    symbol: "고요함 속의 강인함",
    image_url: "blue",
    keywords: ["신체", "문학"],
  },
  {
    flower: "센트레아",
    symbol: "행복, 섬세, 유쾌",
    image_url: "purple",
    keywords: ["희망"],
  },
  {
    flower: "샤스타데이지",
    symbol: "만사는 인내",
    image_url: "white",
    keywords: ["문학"],
  },
  { flower: "서어나무", symbol: "재물", image_url: "red", keywords: ["희망"] },
  {
    flower: "서양모과",
    symbol: "영원한 사랑",
    image_url: "pink",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "서향나무",
    symbol: "불멸, 명예, 꿈 속의 사랑",
    image_url: "blue",
    keywords: ["사랑"],
  },
  {
    flower: "석류",
    symbol: "원숙미, 원숙한 아름다움, 어리석음, 통합",
    image_url: "red",
    keywords: ["문학", "슬픔"],
  },
  {
    flower: "석산(= 피안화)",
    symbol: "슬픈 추억, 잃어버린 기억, 이룰 수 없는 사랑",
    image_url: "grey",
    keywords: ["시간", "문학", "사랑", "슬픔"],
  },
  {
    flower: "선인장",
    symbol: "열정, 정열, 무모한 사랑",
    image_url: "red",
    keywords: ["사랑"],
  },
  { flower: "설강화", symbol: "희망", image_url: "pink", keywords: ["희망"] },
  {
    flower: "설앵초",
    symbol: "수줍움, 천국의 열쇠, 행운의 열쇠",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "세인트폴리아",
    symbol: "작은 사랑",
    image_url: "blue",
    keywords: ["사랑"],
  },
  {
    flower: "세이지",
    symbol: "가정의 평화",
    image_url: "purple",
    keywords: ["가족", "희망"],
  },
  {
    flower: "소귀나무",
    symbol: "그대만을 사랑해요.",
    image_url: "white",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "소나무",
    symbol: "불변, 불멸",
    image_url: "red",
    keywords: ["시간"],
  },
  {
    flower: "소철",
    symbol: "강한 사랑, 속세 비법",
    image_url: "pink",
    keywords: ["사랑"],
  },
  {
    flower: "소태나무",
    symbol: "애교",
    image_url: "yellow",
    keywords: ["신체", "문학", "사랑"],
  },
  {
    flower: "솔송나무",
    symbol: "행복한 마음",
    image_url: "blue",
    keywords: ["희망"],
  },
  {
    flower: "송엽국",
    symbol: "나태",
    image_url: "purple",
    keywords: ["생각", "시간"],
  },
  {
    flower: "쇠서나물",
    symbol: "발랄",
    image_url: "white",
    keywords: ["희망"],
  },
  {
    flower: "수국",
    symbol: "변덕, 진심, 고집, 냉정, 당신은 차갑다",
    image_url: "red",
    keywords: ["생각"],
  },
  {
    flower: "수련",
    symbol: "깨끗한 마음, 청순한 마음",
    image_url: "pink",
    keywords: ["생각"],
  },
  {
    flower: "수레국화(= 센트레아)",
    symbol: "행복",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "수박꽃",
    symbol: "큰 마음",
    image_url: "blue",
    keywords: ["생각"],
  },
  {
    flower: "수선화",
    symbol: "자기애, 자존심, 고결, 신비, 외로움",
    image_url: "purple",
    keywords: ["생각", "슬픔"],
  },
  {
    flower: "순비기나무",
    symbol: "그리움",
    image_url: "white",
    keywords: ["생각"],
  },
  {
    flower: "쉬땅나무",
    symbol: "신중함",
    image_url: "red",
    keywords: ["생각"],
  },
  {
    flower: "스노드롭",
    symbol: "깊은 애정, 희망,당신의 죽음을 기원합니다",
    image_url: "pink",
    keywords: ["죽음", "희망"],
  },
  {
    flower: "스위트피",
    symbol: "기쁨, 가련, 추억(나를 기억해줘요)",
    image_url: "yellow",
    keywords: ["시간", "희망"],
  },
  {
    flower: "스윗오렌지",
    symbol: "열린 마음",
    image_url: "blue",
    keywords: ["생각"],
  },
  {
    flower: "스타티스",
    symbol: "영원한 사랑",
    image_url: "purple",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "스톡크",
    symbol: "믿어주세요",
    image_url: "white",
    keywords: ["생각"],
  },
  {
    flower: "스프랑게리",
    symbol: "항상 변함 없음",
    image_url: "red",
    keywords: ["시간"],
  },
  { flower: "스피리아", symbol: "노력", image_url: "pink", keywords: ["생각"] },
  {
    flower: "스타치스",
    symbol: "영원한 사랑",
    image_url: "yellow",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "스트로벨리",
    symbol: "선견지명",
    image_url: "blue",
    keywords: ["생각", "문학"],
  },
  {
    flower: "스파티필룸",
    symbol: "감싸는 사랑",
    image_url: "purple",
    keywords: ["사랑"],
  },
  {
    flower: "스프랑게리",
    symbol: "항상 변화 없음",
    image_url: "white",
    keywords: ["시간"],
  },
  { flower: "스피리아", symbol: "노력", image_url: "red", keywords: ["생각"] },
  { flower: "시계꽃", symbol: "믿음", image_url: "pink", keywords: ["생각"] },
  { flower: "시금치", symbol: "활력", image_url: "yellow", keywords: ["신체"] },
  {
    flower: "시네라리아",
    symbol: "항상 즐거움, 항상 빛남",
    image_url: "blue",
    keywords: ["희망"],
  },
  {
    flower: "시스투스",
    symbol: "인기, 나는 내일/언젠가 죽겠지",
    image_url: "purple",
    keywords: ["문학"],
  },
  {
    flower: "시클라멘",
    symbol: "수줍음, 질투, 가버린 사랑",
    image_url: "white",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "식나무",
    symbol: "젊고 아름답다",
    image_url: "red",
    keywords: ["생각", "시간", "문학"],
  },
  {
    flower: "신나무",
    symbol: "변치 않는 귀여움",
    image_url: "pink",
    keywords: ["시간", "신체", "문학", "사랑"],
  },
  {
    flower: "싸리꽃",
    symbol: "단정한 사랑",
    image_url: "yellow",
    keywords: ["사랑"],
  },
  {
    flower: "싸리나무",
    symbol: "상념, 사색",
    image_url: "blue",
    keywords: ["생각"],
  },
  {
    flower: "씀바귀",
    symbol: "순박, 헌신함",
    image_url: "purple",
    keywords: ["생각"],
  },
  {
    flower: "쐐기풀",
    symbol: "악의",
    image_url: "white",
    keywords: ["생각", "분노"],
  },
  {
    flower: "싱고니움",
    symbol: "기쁨, 즐거움",
    image_url: "red",
    keywords: ["희망"],
  },
  {
    flower: "쉐플레라",
    symbol: "함께하는 사랑, 행복",
    image_url: "pink",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "아가판더스",
    symbol: "사랑의 전달, 희망",
    image_url: "yellow",
    keywords: ["사랑"],
  },
  { flower: "아게라텀", symbol: "신뢰", image_url: "blue", keywords: ["생각"] },
  {
    flower: "아글라오네마",
    symbol: "부귀, 행복, 행운",
    image_url: "purple",
    keywords: ["희망"],
  },
  {
    flower: "아디언텀",
    symbol: "신명, 애교",
    image_url: "white",
    keywords: ["생각", "희망"],
  },
  {
    flower: "아레카야자",
    symbol: "부활",
    image_url: "red",
    keywords: ["죽음", "신체", "문학"],
  },
  {
    flower: "아로니아",
    symbol: "불로장생, 영원한 사랑",
    image_url: "pink",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "아마존빅토리아수련",
    symbol: "행운",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "아마란스",
    symbol: "시들지 않는 사랑, 애정",
    image_url: "blue",
    keywords: ["사랑"],
  },
  { flower: "아욱", symbol: "은혜", image_url: "purple", keywords: ["희망"] },
  {
    flower: "아이비",
    symbol: "행운이 가득한 사랑",
    image_url: "white",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "아나나스(= 파인애플)",
    symbol: "만족, 미래를 즐긴다",
    image_url: "red",
    keywords: ["희망"],
  },
  {
    flower: "아네모네",
    symbol:
      "기대, 기다림, 고독, 배신, 사랑의 괴로움, 허무한 사랑, 이뤄질 수 없는 사랑, 제 곁에 있어 줘서 고마웠어요. 당신을 사랑하니까 저의 모든 것을 드릴게요. 나는 당신을 영원히 사랑할 거예요. 비록 당신이 날 사랑하지 않더라도 전 당신을 사랑합니다. 나를 잊지 말아주세요.",
    image_url: "pink",
    keywords: ["시간", "문학", "사랑", "슬픔"],
  },
  {
    flower: "아그배나무",
    symbol: "온화",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "아데니움",
    symbol: "무모한 사랑, 정열, 열정",
    image_url: "blue",
    keywords: ["사랑", "공포"],
  },
  {
    flower: "아라비아의 별",
    symbol: "순수",
    image_url: "purple",
    keywords: ["생각"],
  },
  {
    flower: "아르메리아",
    symbol: "배려, 동정, 가련",
    image_url: "white",
    keywords: ["슬픔"],
  },
  {
    flower: "아리스타타",
    symbol: "아름다움의 소유자",
    image_url: "red",
    keywords: ["사랑"],
  },
  { flower: "아마", symbol: "감사", image_url: "pink", keywords: ["희망"] },
  {
    flower: "아마릴리스",
    symbol: "자랑, 수다쟁이, 은은한 아름다움, 인공적, 침묵",
    image_url: "yellow",
    keywords: ["생각", "문학"],
  },
  {
    flower: "아메리칸 블루",
    symbol: "두 사람의 인연",
    image_url: "blue",
    keywords: ["문학", "희망"],
  },
  {
    flower: "아몬드",
    symbol: "진실한 사랑, 희망, 기대",
    image_url: "purple",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "아부틸론",
    symbol: "나는 당신을 영원히 사랑합니다",
    image_url: "white",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "아스타",
    symbol: "믿는 사람, 추억, 보상",
    image_url: "red",
    keywords: ["시간"],
  },
  {
    flower: "아스타 (자주 아스타)",
    symbol: "사랑의 승리",
    image_url: "purple",
    keywords: ["사랑"],
  },
  {
    flower: "아스타 (복숭아색 아스타)",
    symbol: "달콤한 꿈",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "아스타 (파란 아스타)",
    symbol: "신뢰",
    image_url: "blue",
    keywords: ["희망"],
  },
  {
    flower: "아스타 (하얀 아스타)",
    symbol: "나를 믿어주세요",
    image_url: "white",
    keywords: ["문학"],
  },
  {
    flower: "아스파라거스",
    symbol: "무변화, 불변, 영원한 행복",
    image_url: "red",
    keywords: ["시간", "희망"],
  },
  {
    flower: "아스포델",
    symbol: "나는 당신의 것",
    image_url: "pink",
    keywords: ["사랑"],
  },
  {
    flower: "아이비제라늄",
    symbol: "진실한 애정",
    image_url: "yellow",
    keywords: ["사랑"],
  },
  {
    flower: "아잘레아",
    symbol: "사랑의 기쁨, 희망",
    image_url: "blue",
    keywords: ["사랑"],
  },
  {
    flower: "아왜나무",
    symbol: "지옥에 간 목사",
    image_url: "purple",
    keywords: ["문학"],
  },
  {
    flower: "아주가 렙탄스",
    symbol: "순결, 다시 찾은 행복",
    image_url: "white",
    keywords: ["신체", "희망"],
  },
  {
    flower: "아카시아",
    symbol: "쾌락을 바람, 친교, 깨끗한 마음, 우정, 숨겨진 사랑",
    image_url: "white",
    keywords: ["신체", "사랑"],
  },
  {
    flower: "아칸더스",
    symbol: "기교, 복수, 절교",
    image_url: "white",
    keywords: ["분노"],
  },
  {
    flower: "안개꽃",
    symbol: "맑은 마음, 사랑의 성공",
    image_url: "white",
    keywords: ["사랑"],
  },
  {
    flower: "안개꽃 (하얀 안개꽃)",
    symbol: "죽음, 슬픔",
    image_url: "white",
    keywords: ["죽음", "슬픔"],
  },
  {
    flower: "안개꽃 (붉은 안개꽃)",
    symbol: "기쁨의 순간",
    image_url: "red",
    keywords: ["희망"],
  },
  {
    flower: "안개꽃 (자주 안개꽃)",
    symbol: "깨끗한 마음",
    image_url: "purple",
    keywords: ["생각", "희망"],
  },
  {
    flower: "안개꽃 (노란 안개꽃)",
    symbol: "기쁨과 성공",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "안개꽃 (분홍 안개꽃)",
    symbol: "사랑의 성공",
    image_url: "pink",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "안개꽃 (파란 안개꽃)",
    symbol: "영원한 사랑",
    image_url: "blue",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "안개나무",
    symbol: "희망의 내일",
    image_url: "white",
    keywords: ["시간", "희망"],
  },
  {
    flower: "안시리움",
    symbol: "번뇌, 불타는 마음",
    image_url: "pink",
    keywords: ["생각", "슬픔"],
  },
  {
    flower: "안스륨",
    symbol: "사랑에 번민하는 마음",
    image_url: "red",
    keywords: ["생각", "사랑", "슬픔"],
  },
  {
    flower: "안젤로니아",
    symbol: "천사의 얼굴",
    image_url: "pink",
    keywords: ["문학"],
  },
  {
    flower: "안젤리카",
    symbol: "천사의 허브",
    image_url: "yellow",
    keywords: ["문학"],
  },
  {
    flower: "안추사",
    symbol: "당신을 믿을 수 없어요",
    image_url: "blue",
    keywords: ["생각", "분노"],
  },
  {
    flower: "알로에",
    symbol: "꽃도 잎새도, 영원한 건강",
    image_url: "purple",
    keywords: ["시간", "문학"],
  },
  {
    flower: "알리움",
    symbol: "무한한 슬픔, 멀어지는 마음",
    image_url: "white",
    keywords: ["생각", "시간", "슬픔"],
  },
  {
    flower: "알리만다",
    symbol: "희망을 가지세요",
    image_url: "red",
    keywords: ["희망"],
  },
  {
    flower: "알로카시아",
    symbol: "수줍음",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "야로우",
    symbol: "싸움, 변함없는 행복",
    image_url: "yellow",
    keywords: ["시간", "희망", "분노"],
  },
  {
    flower: "애기동백",
    symbol: "겸손, 이상적인 사랑",
    image_url: "blue",
    keywords: ["사랑"],
  },
  {
    flower: "앰브로시아",
    symbol: "행복한 연애",
    image_url: "purple",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "앵두나무",
    symbol: "수줍음",
    image_url: "white",
    keywords: ["희망"],
  },
  {
    flower: "앵초",
    symbol: "젊은 시절과 고뇌",
    image_url: "red",
    keywords: ["시간", "문학"],
  },
  {
    flower: "빨간 앵초",
    symbol: "돌보지 않은 아름다움, 비할 바 없는 아름다움,",
    image_url: "red",
    keywords: ["문학"],
  },
  {
    flower: "옥슬립",
    symbol: "첫사랑",
    image_url: "yellow",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "카우슬립",
    symbol: "젊은 날의 슬픔",
    image_url: "blue",
    keywords: ["시간", "슬픔"],
  },
  {
    flower: "하얀 앵초",
    symbol: "첫사랑, 행복의 열쇠, 가련",
    image_url: "white",
    keywords: ["희망", "사랑", "슬픔"],
  },
  {
    flower: "연근",
    symbol: "당신이 아름다운 것처럼 당신의 마음도 아름답다",
    image_url: "beige",
    keywords: ["문학"],
  },
  {
    flower: "연꽃",
    symbol: "소원해진 사랑",
    image_url: "pink",
    keywords: ["사랑", "슬픔"],
  },
  {
    flower: "연령초",
    symbol: "장수, 열정, 정렬, 고독, 그윽한 마음, 사랑하는 이의 죽음",
    image_url: "blue",
    keywords: ["사랑"],
  },
  {
    flower: "에델바이스",
    symbol: "소중한 추억",
    image_url: "white",
    keywords: ["시간"],
  },
  { flower: "에리카", symbol: "고독", image_url: "white", keywords: ["슬픔"] },
  {
    flower: "에리카 (하얀 에리카)",
    symbol: "보호",
    image_url: "white",
    keywords: ["공포"],
  },
  {
    flower: "에리카 (자주 에리카)",
    symbol: "존경",
    image_url: "purple",
    keywords: ["희망"],
  },
  {
    flower: "에리카 (분홍 에리카)",
    symbol: "행운",
    image_url: "pink",
    keywords: ["희망"],
  },
  { flower: "어성초", symbol: "기다림", image_url: "red", keywords: ["슬픔"] },
  { flower: "억새", symbol: "은퇴", image_url: "pink", keywords: ["슬픔"] },
  { flower: "얼레지", symbol: "질투", image_url: "yellow", keywords: ["분노"] },
  {
    flower: "엉겅퀴",
    symbol: "독립, 엄격, 내핍, 닿지 마세요",
    image_url: "blue",
    keywords: ["공포"],
  },
  {
    flower: "애크메아",
    symbol: "만족",
    image_url: "purple",
    keywords: ["희망"],
  },
  {
    flower: "에리트리나 크리스타갈리",
    symbol: "꿈의 힘",
    image_url: "white",
    keywords: ["문학"],
  },
  {
    flower: "에린지움",
    symbol: "비밀스러운 애정",
    image_url: "red",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "에니시다",
    symbol: "겸손, 청초",
    image_url: "pink",
    keywords: ["생각"],
  },
  {
    flower: "에케베리아",
    symbol: "일곱가지 복이 들어온다",
    image_url: "yellow",
    keywords: ["문학"],
  },
  {
    flower: "에키나시아",
    symbol: "영원한 행복",
    image_url: "blue",
    keywords: ["시간", "희망"],
  },
  {
    flower: "에키놉스",
    symbol: "경계",
    image_url: "purple",
    keywords: ["공포"],
  },
  {
    flower: "예덕나무",
    symbol: "예절과 덕성",
    image_url: "white",
    keywords: ["생각"],
  },
  { flower: "옐로설탄", symbol: "결단", image_url: "red", keywords: ["생각"] },
  {
    flower: "오동나무",
    symbol: "고상",
    image_url: "pink",
    keywords: ["생각", "문학"],
  },
  {
    flower: "오구나무",
    symbol: "등불",
    image_url: "yellow",
    keywords: ["문학"],
  },
  { flower: "오과", symbol: "이면성", image_url: "blue", keywords: ["문학"] },
  {
    flower: "양귀비",
    symbol: "상상(몽상)",
    image_url: "red",
    keywords: ["생각", "문학"],
  },
  {
    flower: "양귀비 (붉은 양귀비)",
    symbol: "몽상(헛된 생각)",
    image_url: "red",
    keywords: ["생각"],
  },
  {
    flower: "양귀비 (하얀 양귀비)",
    symbol: "망각",
    image_url: "white",
    keywords: ["문학"],
  },
  {
    flower: "양귀비 (노란 양귀비)",
    symbol: "풍족함",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "양귀비 (자주 양귀비)",
    symbol: "허영/환상",
    image_url: "purple",
    keywords: ["슬픔"],
  },
  {
    flower: "약쑥",
    symbol: "부재, 쓰라린 슬픔",
    image_url: "red",
    keywords: ["슬픔"],
  },
  {
    flower: "양치",
    symbol: "사랑스러움, 성실, 신뢰",
    image_url: "pink",
    keywords: ["사랑"],
  },
  {
    flower: "영산홍",
    symbol: "첫사랑",
    image_url: "yellow",
    keywords: ["사랑"],
  },
  { flower: "오레가노", symbol: "기쁨", image_url: "blue", keywords: ["희망"] },
  {
    flower: "오렌지",
    symbol: "새색시의 기쁨, 순결, 너그러운 마음",
    image_url: "purple",
    keywords: ["가족", "희망"],
  },
  {
    flower: "오리나무",
    symbol: "장엄, 위로",
    image_url: "white",
    keywords: ["생각", "문학", "감각"],
  },
  {
    flower: "오이풀",
    symbol: "변화, 존경",
    image_url: "red",
    keywords: ["생각", "시간"],
  },
  {
    flower: "옥수수",
    symbol: "재물, 보물, 금은보화, 일획천금",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "옥잠화",
    symbol: "소박, 추억, 침착하고 조용함",
    image_url: "yellow",
    keywords: ["생각", "시간", "희망"],
  },
  {
    flower: "온시디움",
    symbol: "순박한 마음",
    image_url: "blue",
    keywords: ["생각", "자연"],
  },
  {
    flower: "올리브나무",
    symbol: "평화",
    image_url: "purple",
    keywords: ["희망"],
  },
  {
    flower: "용담",
    symbol: "슬픈 그대가 좋아",
    image_url: "white",
    keywords: ["문학"],
  },
  {
    flower: "용설란",
    symbol: "강한 의지, 용기, 섬세",
    image_url: "red",
    keywords: ["생각", "희망"],
  },
  { flower: "용수초", symbol: "온순", image_url: "pink", keywords: ["희망"] },
  {
    flower: "왕대",
    symbol: "정절, 신념",
    image_url: "yellow",
    keywords: ["생각"],
  },
  {
    flower: "우엉",
    symbol: "괴롭히지 말아요, 인격자",
    image_url: "blue",
    keywords: ["문학"],
  },
  {
    flower: "울금",
    symbol: "당신을 따르겠습니다",
    image_url: "red",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "유동나무",
    symbol: "기름장수",
    image_url: "pink",
    keywords: ["문학"],
  },
  {
    flower: "유자나무",
    symbol: "기쁜소식",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "유채꽃",
    symbol: "명랑, 쾌활",
    image_url: "yellow",
    keywords: ["신체", "희망"],
  },
  {
    flower: "유카꽃",
    symbol: "위험, 접근하지 마세요",
    image_url: "purple",
    keywords: ["생각", "문학", "공포"],
  },
  {
    flower: "유칼립투스",
    symbol: "추억",
    image_url: "white",
    keywords: ["시간"],
  },
  {
    flower: "유리호프스",
    symbol: "온화함, 청아한 당신",
    image_url: "red",
    keywords: ["생각"],
  },
  {
    flower: "유홍초",
    symbol: "영원히 사랑스러워",
    image_url: "pink",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "윤노리나무",
    symbol: "전통",
    image_url: "yellow",
    keywords: ["생각"],
  },
  {
    flower: "원추리",
    symbol: "기다리는 마음",
    image_url: "blue",
    keywords: ["문학", "슬픔"],
  },
  { flower: "월계수", symbol: "명예", image_url: "purple", keywords: ["희망"] },
  {
    flower: "월하미인",
    symbol: "밤의 고독, 단 한 번이라도, 단 한 번뿐인 사랑, 서로뿐인 사랑",
    image_url: "white",
    keywords: ["문학", "사랑", "슬픔"],
  },
  { flower: "으름덩굴", symbol: "재능", image_url: "red", keywords: ["희망"] },
  {
    flower: "은매화",
    symbol: "사랑의 속삭임",
    image_url: "pink",
    keywords: ["사랑"],
  },
  { flower: "은목서", symbol: "유혹", image_url: "red", keywords: ["사랑"] },
  {
    flower: "은방울꽃",
    symbol: "섬세함, 언젠가 반드시 행복해질겁니다, 희망, 순애, 행복의 방문",
    image_url: "pink",
    keywords: ["시간", "문학", "희망"],
  },
  { flower: "은백양", symbol: "슬픔", image_url: "yellow", keywords: ["슬픔"] },
  { flower: "은사철", symbol: "지혜", image_url: "blue", keywords: ["생각"] },
  {
    flower: "은행나무",
    symbol: "진혼, 정적, 장엄, 장수, 정숙",
    image_url: "yellow",
    keywords: ["생각"],
  },
  { flower: "이끼", symbol: "모성애", image_url: "white", keywords: ["가족"] },
  {
    flower: "이팝나무",
    symbol: "영원한 사랑, 자기 향상",
    image_url: "red",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "인디고",
    symbol: "사랑을 노래하는 꽃",
    image_url: "pink",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "인동초",
    symbol:
      "부성애, 우애, 헌신적인 사랑, 사랑의 인연, 슬퍼하고 있는 당신이 매우 좋다",
    image_url: "yellow",
    keywords: ["가족", "문학", "사랑"],
  },
  {
    flower: "일본잎갈나무",
    symbol: "대담, 용기",
    image_url: "blue",
    keywords: ["생각"],
  },
  {
    flower: "일일초",
    symbol: "당신을 사랑합니다, 즐거운 추억, 우정",
    image_url: "purple",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "일랑일랑",
    symbol: "화려함, 사치스러움",
    image_url: "white",
    keywords: ["감각"],
  },
  {
    flower: "임파첸스",
    symbol: "나의 사랑은 당신보다 깊다",
    image_url: "red",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "잇꽃(=홍화)",
    symbol: "불변, 무심(無心), 당신을 물들이다",
    image_url: "pink",
    keywords: ["생각", "문학"],
  },
  {
    flower: "엔젤트럼펫",
    symbol: "덧없는 사랑",
    image_url: "yellow",
    keywords: ["시간", "사랑", "슬픔"],
  },
  {
    flower: "엘라티오르베고니아",
    symbol: "진정한 아름다움",
    image_url: "blue",
    keywords: ["사랑"],
  },
  { flower: "여로", symbol: "기다림", image_url: "purple", keywords: ["슬픔"] },
  {
    flower: "오스테오그체르뭄",
    symbol: "영원한 사랑, 원기, 행복",
    image_url: "white",
    keywords: ["시간", "희망", "사랑"],
  },
  { flower: "오크라", symbol: "번영", image_url: "red", keywords: ["희망"] },
  {
    flower: "오텀 세이지",
    symbol: "건강, 장수, 미덕",
    image_url: "pink",
    keywords: ["신체", "희망"],
  },
  {
    flower: "옥살리스",
    symbol: "기쁨, 빛나는 마음, 당신과 함께 살다",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "유리오프스",
    symbol: "영원한 아름다움, 청아한 당신",
    image_url: "blue",
    keywords: ["시간"],
  },
  {
    flower: "유스토마",
    symbol: "영원한 사랑",
    image_url: "purple",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "유포르비아",
    symbol: "박애",
    image_url: "white",
    keywords: ["사랑"],
  },
  {
    flower: "이베리스",
    symbol: "깨끗함, 우아함, 첫사랑의 추억",
    image_url: "red",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "이스라지",
    symbol: "수줍음, 오로지 한 사랑",
    image_url: "pink",
    keywords: ["사랑"],
  },
  {
    flower: "장미 (붉은 장미)",
    symbol: "사랑, 아름다움, 낭만적인 사랑, 용기, 존경, 열망, 열정",
    image_url: "red",
    keywords: ["사랑"],
  },
  {
    flower: "장미 (버건디 장미)",
    symbol: "무의식적인 아름다움",
    image_url: "red",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "장미 (하얀 장미)",
    symbol: "순수, 결백, 젊음, 영성, 숭배",
    image_url: "white",
    keywords: ["생각", "문학"],
  },
  {
    flower: "장미 (분홍 장미)",
    symbol: "감탄, 감사, 성실, 우아함, 사랑의 맹세",
    image_url: "pink",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "장미 (옅은 분홍 장미)",
    symbol: "존경, 연민, 온화함, 다정함, 나의 마음 그대만이 아네, 찬양",
    image_url: "pink",
    keywords: ["문학", "희망"],
  },
  {
    flower: "장미 (짙은 분홍 장미)",
    symbol: "감탄, 감사, 고마워요",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "장미 (복숭아색 장미)",
    symbol: "열망",
    image_url: "pink",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "장미 (옅은 복숭아색 장미)",
    symbol: "겸손",
    image_url: "pink",
    keywords: ["생각"],
  },
  {
    flower: "장미 (산호색 장미)",
    symbol: "존경",
    image_url: "red",
    keywords: ["생각"],
  },
  {
    flower: "장미 (노란 장미)",
    symbol:
      "이별, 변하지 않는 사랑, 기쁨, 우정, 질투, 환영, 영원한 우정과 사랑",
    image_url: "yellow",
    keywords: ["시간", "사랑", "슬픔"],
  },
  {
    flower: "장미 (주황 장미)",
    symbol: "욕망, 열광, 열정, 매료",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "장미 (자주 장미)",
    symbol: "황홀함, 장엄함",
    image_url: "purple",
    keywords: ["희망"],
  },
  {
    flower: "장미 (라벤더색 장미)",
    symbol: "첫눈에 빠진 사랑",
    image_url: "purple",
    keywords: ["사랑"],
  },
  {
    flower: "장미 (검은 장미)",
    symbol: "저주, 죽음, 이별, 당신은 영원히 나만의 것",
    image_url: "purple",
    keywords: ["죽음", "시간", "문학"],
  },
  {
    flower: "장미 (푸른 장미)",
    symbol: "얻을 수 없는 것, 불가능한 것 → 기적, 포기하지 않는 사랑",
    image_url: "blue",
    keywords: ["문학", "희망", "사랑"],
  },
  {
    flower: "장미 (초록 장미)",
    symbol: "천상에만 존재하는 고귀한 사랑",
    image_url: "blue",
    keywords: ["사랑"],
  },
  {
    flower: "자스민",
    symbol: "행운을 빌어요, 행복, 친절, 상냥한, 관능적, 사랑의 기쁨, 애교",
    image_url: "white",
    keywords: ["문학", "희망", "사랑"],
  },
  {
    flower: "자스민 (하얀 자스민)",
    symbol: "당신은 나의 것, 사랑스러움, 관능적",
    image_url: "white",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "자스민 (노란 자스민)",
    symbol: "은총, 우아함",
    image_url: "yellow",
    keywords: ["문학", "감각", "희망"],
  },
  {
    flower: "발렌타인 자스민",
    symbol: "사랑을 위해 멋을 부린 남자",
    image_url: "purple",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "브룬펠시아 자스민",
    symbol: "사랑스러움, 당신은 나의 것",
    image_url: "purple",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "차이니스 자스민",
    symbol: "당신은 나의 것, 사랑의 기쁨",
    image_url: "white",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "제비꽃",
    symbol: "성실, 겸양",
    image_url: "purple",
    keywords: ["생각"],
  },
  {
    flower: "제비꽃 (보란 제비꽃)",
    symbol: "겸손, 성실, 사랑",
    image_url: "purple",
    keywords: ["사랑"],
  },
  {
    flower: "제비꽃 (노란 제비꽃)",
    symbol: "수줍은 사랑, 시골의 행복, 작은 기쁨",
    image_url: "yellow",
    keywords: ["자연", "희망", "사랑"],
  },
  {
    flower: "제비꽃 (하얀 제비꽃)",
    symbol: "순진무구한 사랑, 순결, 천진난만한 사랑",
    image_url: "white",
    keywords: ["자연", "사랑"],
  },
  {
    flower: "제비꽃 (파란 제비꽃)",
    symbol: "사랑",
    image_url: "blue",
    keywords: ["사랑"],
  },
  {
    flower: "제비꽃 (분홍 제비꽃)",
    symbol: "희망",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "흰젖 제비꽃",
    symbol: "순진한 사랑",
    image_url: "white",
    keywords: ["사랑"],
  },
  {
    flower: "접시꽃",
    symbol: "열렬한 연애, 풍요, 야망, 평안, 다산, 애절한 사랑, 집보기",
    image_url: "purple",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "접시꽃 (흰색 접시꽃)",
    symbol: "단순, 평안, 단순한 사랑, 아양 떠는 사랑",
    image_url: "white",
    keywords: ["집", "사랑"],
  },
  {
    flower: "접시꽃 (검은 접시꽃)",
    symbol: "나는 사랑에 불탄다.",
    image_url: "black",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "제라늄",
    symbol: "그대와 함께하는 행복, 친구의 정, 결심",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "제라늄 (붉은 제라늄)",
    symbol: "그대가 있어 사랑이 있네, 그대를 사랑합니다",
    image_url: "red",
    keywords: ["사랑"],
  },
  {
    flower: "제라늄 (로즈 제라늄)",
    symbol: "그대로 인한 행복",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "제라늄 (하얀 제라늄)",
    symbol: "저는 당신의 사랑을 신뢰하지 않습니다",
    image_url: "white",
    keywords: ["생각", "사랑", "분노"],
  },
  {
    flower: "제라늄 (분홍 제라늄)",
    symbol: "결심, 결의",
    image_url: "pink",
    keywords: ["생각"],
  },
  {
    flower: "빨강무늬 제라늄",
    symbol:
      "쓸쓸한 사람이나 슬픈 사람들을 보면 어떻게서든 위로해주고 싶어하는 당신 자신도 쓸쓸해 하는 사람이군요",
    image_url: "red",
    keywords: ["문학", "슬픔"],
  },
  {
    flower: "종려나무",
    symbol: "승리, 쟁취",
    image_url: "blue",
    keywords: ["희망"],
  },
  {
    flower: "자작나무",
    symbol: "당신을 기다립니다.",
    image_url: "white",
    keywords: ["생각", "슬픔"],
  },
  {
    flower: "전나무",
    symbol: "숭고, 정직, 승진, 고상함, 장엄",
    image_url: "red",
    keywords: ["생각"],
  },
  {
    flower: "조팝나무",
    symbol: "노련하다, 선언, 단정한 사랑, 당신의 생각대로입니다, 헛수고, 노력",
    image_url: "pink",
    keywords: ["사랑"],
  },
  {
    flower: "주목나무",
    symbol: "비애, 죽음, 명예, 고상함",
    image_url: "yellow",
    keywords: ["죽음", "슬픔"],
  },
  {
    flower: "진달래",
    symbol: "절제, 청렴, 사랑의 즐거움, 사랑의 희열, 사랑의 기쁨",
    image_url: "blue",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "점나도나물",
    symbol: "순진",
    image_url: "purple",
    keywords: ["생각"],
  },
  {
    flower: "쥐꼬리 망초",
    symbol: "가련미의 극치",
    image_url: "white",
    keywords: ["생각", "신체", "문학", "슬픔"],
  },
  {
    flower: "자운영",
    symbol: "나의 행복, 그대의 관대한 사랑, 감화",
    image_url: "red",
    keywords: ["문학", "희망", "사랑"],
  },
  {
    flower: "중국패모",
    symbol: "위엄",
    image_url: "pink",
    keywords: ["문학", "감각"],
  },
  {
    flower: "자목련",
    symbol:
      "자연애, 은혜, 존경, 꽃피는 따뜻한 봄, 소중한 이웃님들 편안하시기를",
    image_url: "yellow",
    keywords: ["문학", "희망"],
  },
  {
    flower: "좁은 입배 풍동",
    symbol: "참을 수 없어",
    image_url: "blue",
    keywords: ["생각", "문학"],
  },
  {
    flower: "짚신나물",
    symbol: "감사",
    image_url: "purple",
    keywords: ["희망"],
  },
  {
    flower: "저먼더",
    symbol: "경애, 담백",
    image_url: "white",
    keywords: ["생각"],
  },
  {
    flower: "자양화",
    symbol: "당신은 아름답지만 차갑다, 냉정, 무정, 냉담, 변덕, 변심, 소녀의 꿈",
    image_url: "red",
    keywords: ["생각", "문학"],
  },
  {
    flower: "자몽나무",
    symbol: "따뜻한 에너지가 넘치는 사람",
    image_url: "pink",
    keywords: ["희망"],
  },
  { flower: "잣나무", symbol: "만족", image_url: "yellow", keywords: ["희망"] },
  {
    flower: "주니퍼베리",
    symbol: "보호",
    image_url: "blue",
    keywords: ["생각", "신체"],
  },
  {
    flower: "찔레꽃",
    symbol: "온화, 고독, 자매의 우애, 신중한 사랑, 가족에 대한 그리움",
    image_url: "purple",
    keywords: ["가족", "사랑", "슬픔"],
  },
  {
    flower: "중국 단풍나무",
    symbol: "게으름뱅이",
    image_url: "white",
    keywords: ["신체", "문학"],
  },
  {
    flower: "주머니꽃",
    symbol: "관능적 아름다움, 도움, 나의 재산을 드립니다, 당신을 따르겠습니다",
    image_url: "red",
    keywords: ["문학"],
  },
  {
    flower: "작약",
    symbol: "수줍음, 부끄러움",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "제충국",
    symbol: "청정, 고결, 죽어서도 당신을 지킬게요",
    image_url: "yellow",
    keywords: ["죽음", "문학"],
  },
  {
    flower: "좀깨잎나무",
    symbol: "사랑의 흔적",
    image_url: "blue",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "조록나무",
    symbol: "변하기 쉬운 사랑",
    image_url: "purple",
    keywords: ["문학", "사랑", "공포"],
  },
  {
    flower: "쪽동백나무",
    symbol: "잃어버린 시간을 찾아서",
    image_url: "white",
    keywords: ["시간", "문학"],
  },
  {
    flower: "제니스타",
    symbol: "겸손, 청초",
    image_url: "red",
    keywords: ["생각"],
  },
  {
    flower: "참나리",
    symbol: "깨끗한 마음",
    image_url: "pink",
    keywords: ["자연", "희망"],
  },
  {
    flower: "창포",
    symbol: "희망, 인내, 당신을 믿습니다",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "채송화",
    symbol: "가련함, 순진, 천진난만",
    image_url: "red",
    keywords: ["생각", "문학"],
  },
  {
    flower: "천인국",
    symbol: "단결, 협력",
    image_url: "purple",
    keywords: ["생각"],
  },
  {
    flower: "천일홍",
    symbol: "불변, 매혹, 변치 않는 사랑",
    image_url: "white",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "천수국",
    symbol: "이별의 슬픔과 절망, 죽은 사람에 대한 기억과 축복",
    image_url: "red",
    keywords: ["죽음", "슬픔"],
  },
  {
    flower: "철쭉",
    symbol: "자제, 사랑의 즐거움",
    image_url: "pink",
    keywords: ["생각", "희망", "사랑"],
  },
  {
    flower: "초피나무",
    symbol: "청출어람",
    image_url: "yellow",
    keywords: ["생각", "문학"],
  },
  {
    flower: "층꽃나무",
    symbol: "기도하는 가을여인",
    image_url: "plum",
    keywords: ["문학"],
  },
  {
    flower: "치자나무",
    symbol: "청결, 순결, 행복, 한없는 즐거움",
    image_url: "red",
    keywords: ["희망"],
  },
  {
    flower: "칡꽃",
    symbol: "사랑의 한숨",
    image_url: "pink",
    keywords: ["사랑", "슬픔"],
  },
  {
    flower: "층층나무",
    symbol: "인내력",
    image_url: "yellow",
    keywords: ["생각", "신체"],
  },
  {
    flower: "카우슬립 앵초",
    symbol: "젊은날의 슬픔",
    image_url: "blue",
    keywords: ["시간", "슬픔"],
  },
  {
    flower: "카나리아야자",
    symbol: "부활, 승리",
    image_url: "purple",
    keywords: ["희망"],
  },
  {
    flower: "카틀레야",
    symbol: "당신은 아름답다",
    image_url: "white",
    keywords: ["사랑"],
  },
  {
    flower: "칸나",
    symbol: "존경, 정열, 해피 엔딩, 행복한 종말",
    image_url: "red",
    keywords: ["문학", "희망"],
  },
  {
    flower: "칼라",
    symbol: "천년의 사랑, 순결, 순수, 열정, 청결",
    image_url: "pink",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "칼라디움",
    symbol: "기쁨, 즐거움, 환희",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "칼란디바",
    symbol: "설렘, 순애",
    image_url: "blue",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "칼리스트몬",
    symbol: "결백, 청경, 우정, 사랑의 소식",
    image_url: "purple",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "칼랑코에",
    symbol: "설렘",
    image_url: "white",
    keywords: ["희망"],
  },
  {
    flower: "캄파눌라",
    symbol: "따뜻한 사랑, 변하지 않는다, 상냥한 사랑, 만족, 감사",
    image_url: "red",
    keywords: ["문학", "사랑"],
  },
  { flower: "컴프리", symbol: "낯설음", image_url: "pink", keywords: ["생각"] },
  {
    flower: "코리달리스",
    symbol: "보물주머니, 비밀, 희소식",
    image_url: "yellow",
    keywords: ["문학", "희망"],
  },
  {
    flower: "코스모스",
    symbol: "소녀의 순결, 순정",
    image_url: "red",
    keywords: ["사랑"],
  },
  {
    flower: "콩",
    symbol: "반드시 오고야 말 행복, 시시콜콜한 보람",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "크로커스 (하얀 크로커스)",
    symbol: "후회 없는 청춘, 믿는 기쁨, 당신을 기다립니다",
    image_url: "white",
    keywords: ["시간", "희망"],
  },
  {
    flower: "크로커스 (보라 크로커스)",
    symbol: "너는 날 사랑한 것을 후회하고 있어",
    image_url: "purple",
    keywords: ["생각", "슬픔"],
  },
  {
    flower: "크랜베리",
    symbol: "마음의 고통을 위로하다",
    image_url: "red",
    keywords: ["슬픔"],
  },
  {
    flower: "클로버",
    symbol: "약속, 행운, 평화",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "레드 클로버",
    symbol: "행복, 약속, 너와 함께, 나를 생각해 주오",
    image_url: "red",
    keywords: ["시간", "희망", "사랑"],
  },
  {
    flower: "클레마티스",
    symbol: "노력",
    image_url: "blue",
    keywords: ["생각"],
  },
  {
    flower: "카네이션 (노란 카네이션)",
    symbol: "경멸",
    image_url: "yellow",
    keywords: ["분노"],
  },
  {
    flower: "카네이션 (분홍 카네이션)",
    symbol: "열애",
    image_url: "pink",
    keywords: ["사랑"],
  },
  {
    flower: "카네이션 (빨간 카네이션)",
    symbol: "건강",
    image_url: "red",
    keywords: ["신체"],
  },
  {
    flower: "카네이션 (하얀 카네이션)",
    symbol: "나의 애정은 살아있습니다(죽은 사람을 향해)",
    image_url: "white",
    keywords: ["죽음", "문학"],
  },
  {
    flower: "카모밀레",
    symbol: "고난 속의 힘, 역경을 견디는 힘",
    image_url: "red",
    keywords: ["생각", "희망", "공포"],
  },
  {
    flower: "코키아",
    symbol: "겸허, 청초한 미인, 고백",
    image_url: "pink",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "코리앤더",
    symbol: "숨은 가치",
    image_url: "yellow",
    keywords: ["생각"],
  },
  {
    flower: "큐벤시스",
    symbol: "똑같음, 기억, 추억",
    image_url: "blue",
    keywords: ["시간", "문학"],
  },
  {
    flower: "콜레우스",
    symbol: "절망적인 사랑",
    image_url: "purple",
    keywords: ["사랑", "슬픔"],
  },
  {
    flower: "쿠르시아",
    symbol: "고결, 당신을 저버리지 않습니다, 순수",
    image_url: "white",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "쿠페아",
    symbol: "세심한 사랑",
    image_url: "red",
    keywords: ["사랑"],
  },
  {
    flower: "크레마티스",
    symbol: "마음 아름다움",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "크레오메",
    symbol: "불안정, 인연을 맺음",
    image_url: "yellow",
    keywords: ["사랑", "공포"],
  },
  {
    flower: "크로웨아",
    symbol: "그리움, 애교",
    image_url: "blue",
    keywords: ["신체", "슬픔"],
  },
  {
    flower: "크로톤",
    symbol: "교태, 오염, 질색",
    image_url: "purple",
    keywords: ["감각", "공포"],
  },
  {
    flower: "크립탄서스",
    symbol: "만족",
    image_url: "white",
    keywords: ["희망"],
  },
  {
    flower: "크래손",
    symbol: "안정성, 힘",
    image_url: "red",
    keywords: ["신체"],
  },
  {
    flower: "황색 카틀레아",
    symbol: "경멸",
    image_url: "yellow",
    keywords: ["분노"],
  },
  {
    flower: "카사블랑카",
    symbol: "당신을 진정 사랑하기에 떠나보내겠습니다.",
    image_url: "red",
    keywords: ["문학", "사랑", "슬픔"],
  },
  {
    flower: "키오녹독사",
    symbol: "그리움, 순수한 사랑",
    image_url: "pink",
    keywords: ["사랑"],
  },
  {
    flower: "킹빈자민",
    symbol: "번영, 번창",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "타라곤",
    symbol: "불편하는 호기심",
    image_url: "blue",
    keywords: ["생각", "문학", "분노"],
  },
  {
    flower: "털머위",
    symbol: "한결같은 마음, 다시 찾은 사랑",
    image_url: "purple",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "투구꽃",
    symbol: "밤의 열림, 나를 건드리지 마세요.",
    image_url: "white",
    keywords: ["문학", "공포"],
  },
  {
    flower: "튜베로즈",
    symbol: "위험한 쾌락",
    image_url: "red",
    keywords: ["감각", "희망", "공포"],
  },
  {
    flower: "튤립 (붉은 튤립)",
    symbol: "사랑의 고백",
    image_url: "red",
    keywords: ["사랑"],
  },
  {
    flower: "튤립 (주황 튤립)",
    symbol: "수줍음, 부끄러움",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "튤립 (노란 튤립)",
    symbol: "혼자 하는 사랑, 헛사랑, 사랑의 표식",
    image_url: "yellow",
    keywords: ["사랑", "슬픔"],
  },
  {
    flower: "튤립 (하얀 튤립)",
    symbol: "실연, 용서, 사과",
    image_url: "white",
    keywords: ["슬픔"],
  },
  {
    flower: "튤립 (분홍 튤립)",
    symbol: "애정, 배려",
    image_url: "pink",
    keywords: ["사랑"],
  },
  {
    flower: "튤립 (보라 튤립)",
    symbol: "영원한 사랑, 영원하지 않은 사랑",
    image_url: "purple",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "튤립 (검은 튤립)",
    symbol: "당신을 저주합니다",
    image_url: "purple",
    keywords: ["분노"],
  },
  {
    flower: "망고튤립",
    symbol: "수줍게 하는 사랑의 표시",
    image_url: "red",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "토레니아",
    symbol: "가련한 욕망",
    image_url: "pink",
    keywords: ["생각", "슬픔"],
  },
  { flower: "트리안", symbol: "추억", image_url: "yellow", keywords: ["시간"] },
  {
    flower: "트리터마",
    symbol: "그것을 믿을 수 없다",
    image_url: "blue",
    keywords: ["생각", "문학"],
  },
  {
    flower: "티버치나",
    symbol: "말광량이, 요란한 미인",
    image_url: "purple",
    keywords: ["문학"],
  },
  {
    flower: "틸란드시아",
    symbol: "불멸의 사랑",
    image_url: "white",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "틸란드리아 시아네오",
    symbol: "불멸의 사랑, 불구",
    image_url: "red",
    keywords: ["시간", "신체", "사랑"],
  },
  {
    flower: "파리지옥",
    symbol: "유혹, 영원불변",
    image_url: "pink",
    keywords: ["시간"],
  },
  {
    flower: "파피오페딜럼",
    symbol: "당신의 꿈이 이루어지기를",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "파인",
    symbol: "고독, 용감, 영원불멸",
    image_url: "blue",
    keywords: ["시간"],
  },
  {
    flower: "팔손이나무",
    symbol: "비밀",
    image_url: "purple",
    keywords: ["생각"],
  },
  {
    flower: "팥꽃나무",
    symbol: "달콤한 사랑",
    image_url: "white",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "팥배나무",
    symbol: "매혹",
    image_url: "red",
    keywords: ["생각", "감각", "사랑"],
  },
  {
    flower: "패랭이꽃",
    symbol: "순결한 사랑, 재능, 거절",
    image_url: "pink",
    keywords: ["신체", "사랑"],
  },
  {
    flower: "팬지",
    symbol: "나를 생각해주세요",
    image_url: "yellow",
    keywords: ["생각", "문학", "사랑"],
  },
  {
    flower: "팬넬",
    symbol: "감언이설",
    image_url: "blue",
    keywords: ["생각", "문학"],
  },
  {
    flower: "팽나무",
    symbol: "고귀함",
    image_url: "purple",
    keywords: ["생각", "신체", "문학", "감각"],
  },
  {
    flower: "페르시아국화",
    symbol: "경쟁심",
    image_url: "white",
    keywords: ["생각"],
  },
  {
    flower: "페리윙클",
    symbol: "행복한 추억",
    image_url: "red",
    keywords: ["시간", "희망"],
  },
  {
    flower: "페퍼민트",
    symbol: "온전한 사랑,진심",
    image_url: "pink",
    keywords: ["사랑"],
  },
  {
    flower: "포도나무",
    symbol: "기쁨, 박애, 자선",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "포인세티아",
    symbol: "축하(합니다)",
    image_url: "blue",
    keywords: ["희망"],
  },
  {
    flower: "포플러(=미루나무)",
    symbol: "비탄, 애석",
    image_url: "purple",
    keywords: ["슬픔"],
  },
  {
    flower: "폼폼국화",
    symbol: "진실",
    image_url: "white",
    keywords: ["생각"],
  },
  {
    flower: "푸조나무",
    symbol: "소중함",
    image_url: "red",
    keywords: ["사랑"],
  },
  {
    flower: "풍란",
    symbol: "참다운 매력",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "프랑킨센스",
    symbol: "몽상가",
    image_url: "yellow",
    keywords: ["생각"],
  },
  {
    flower: "프리뮬라",
    symbol:
      "소년 시절의 희망, 젊은 시절의 고뇌, 부귀, 자만, 행복, 모순, 돌보지 않은 아름다움",
    image_url: "blue",
    keywords: ["생각", "자연", "시간", "희망", "슬픔"],
  },
  {
    flower: "프리지아",
    symbol: "천진난만, 자기자랑, 영원한 우정",
    image_url: "purple",
    keywords: ["시간", "문학", "희망"],
  },
  {
    flower: "플라타너스",
    symbol: "천재, 화해, 용서, 휴식",
    image_url: "white",
    keywords: ["생각", "희망"],
  },
  { flower: "플럼바고", symbol: "화해", image_url: "red", keywords: ["희망"] },
  {
    flower: "피나무",
    symbol: "부부애",
    image_url: "pink",
    keywords: ["가족", "사랑"],
  },
  {
    flower: "피안화",
    symbol: "이룰수 없는 사랑, 슬픈 과거",
    image_url: "yellow",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "파키라",
    symbol: "행복, 행운",
    image_url: "blue",
    keywords: ["희망"],
  },
  {
    flower: "파키스타키스루테아",
    symbol: "열망",
    image_url: "purple",
    keywords: ["생각", "사랑"],
  },
  {
    flower: "필로덴드론",
    symbol: "나를 사랑해주세요",
    image_url: "white",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "파루비스",
    symbol: "정직한 사랑",
    image_url: "red",
    keywords: ["생각", "문학", "사랑"],
  },
  {
    flower: "페둔쿨라타라티아",
    symbol: "밀회, 순수",
    image_url: "pink",
    keywords: ["사랑"],
  },
  {
    flower: "페라고늄랜디",
    symbol: "애정, 우정",
    image_url: "yellow",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "팔손이나무",
    symbol: "교활, 기만, 분별, 비밀",
    image_url: "blue",
    keywords: ["분노"],
  },
  {
    flower: "팜파스그라스",
    symbol: "웅대, 자랑스럽다",
    image_url: "purple",
    keywords: ["생각", "감각", "희망"],
  },
  {
    flower: "페튜니아",
    symbol: "당신과 있으면 마음이 편해짐",
    image_url: "white",
    keywords: ["희망"],
  },
  {
    flower: "폰테데리아",
    symbol: "흔들린 기억",
    image_url: "red",
    keywords: ["생각", "시간"],
  },
  {
    flower: "하늘나리",
    symbol: "변치 않은 귀여움",
    image_url: "red",
    keywords: ["시간", "신체", "문학", "사랑"],
  },
  {
    flower: "할미꽃",
    symbol: "슬픈 추억, 슬픔",
    image_url: "pink",
    keywords: ["시간", "슬픔"],
  },
  {
    flower: "향기별꽃",
    symbol: "순수, 화해, 용서, 관용",
    image_url: "yellow",
    keywords: ["희망"],
  },
  {
    flower: "향나무",
    symbol: "영원한 향기",
    image_url: "blue",
    keywords: ["시간", "감각"],
  },
  { flower: "향쑥", symbol: "방심", image_url: "purple", keywords: ["공포"] },
  { flower: "해당화", symbol: "원망", image_url: "white", keywords: ["분노"] },
  {
    flower: "해바라기",
    symbol:
      "애모(愛募), 동경, 숭배, 기다림, 자부심, 자존심,당신만을 바라봅니다.",
    image_url: "red",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "해오라비난초",
    symbol: "꿈 속에서라도 보고 싶다",
    image_url: "pink",
    keywords: ["문학"],
  },
  {
    flower: "허니플랜트",
    symbol: "인생의 출발",
    image_url: "yellow",
    keywords: ["생각"],
  },
  {
    flower: "헬리오트롭",
    symbol: "사랑과 헌신",
    image_url: "blue",
    keywords: ["사랑"],
  },
  {
    flower: "헬리오트로프",
    symbol: "성실, 헌신, 사랑이여 영원하라",
    image_url: "purple",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "헬레보러스",
    symbol: "존재, 추억, 나를 달래주오",
    image_url: "white",
    keywords: ["시간"],
  },
  {
    flower: "현호색",
    symbol: "비밀, 보물주머니",
    image_url: "red",
    keywords: ["생각"],
  },
  {
    flower: "협죽도",
    symbol: "위험, 방심은 금물",
    image_url: "pink",
    keywords: ["생각", "공포"],
  },
  {
    flower: "호두나무",
    symbol: "지성",
    image_url: "yellow",
    keywords: ["생각"],
  },
  {
    flower: "호랑가시나무",
    symbol: "가정의 행복, 평화",
    image_url: "blue",
    keywords: ["가족"],
  },
  {
    flower: "호랑이꽃(= 참나리)",
    symbol: "나를 사랑해주세요",
    image_url: "purple",
    keywords: ["사랑"],
  },
  {
    flower: "호박꽃",
    symbol: "관대함, 포용, 해독, 사랑의 용기",
    image_url: "white",
    keywords: ["사랑"],
  },
  { flower: "호자나무", symbol: "공존", image_url: "red", keywords: ["생각"] },
  {
    flower: "호접란",
    symbol: "애정의 표시",
    image_url: "pink",
    keywords: ["사랑"],
  },
  {
    flower: "흑단",
    symbol: "위선, 암흑",
    image_url: "yellow",
    keywords: ["생각"],
  },
  {
    flower: "흑법사",
    symbol: "영원히, 좋은 예감",
    image_url: "blue",
    keywords: ["시간"],
  },
  { flower: "홉", symbol: "불공평", image_url: "purple", keywords: ["생각"] },
  {
    flower: "회나무",
    symbol: "위험한 장난",
    image_url: "white",
    keywords: ["공포"],
  },
  {
    flower: "회화나무",
    symbol: "망향",
    image_url: "red",
    keywords: ["생각", "공간"],
  },
  {
    flower: "회향",
    symbol: "극찬, 역량",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "황금",
    symbol: "고귀함",
    image_url: "yellow",
    keywords: ["신체", "문학"],
  },
  { flower: "황금싸리", symbol: "겸손", image_url: "blue", keywords: ["생각"] },
  {
    flower: "황새냉이",
    symbol: "그대에게 바칩니다, 사무치는 그리움",
    image_url: "purple",
    keywords: ["문학", "사랑"],
  },
  {
    flower: "활나물",
    symbol: "행복감",
    image_url: "white",
    keywords: ["희망"],
  },
  {
    flower: "히비스커스",
    symbol: "섬세한 아름다움, 남몰래 간직한 사랑",
    image_url: "red",
    keywords: ["사랑"],
  },
  {
    flower: "히솝",
    symbol: "청결, 축제",
    image_url: "pink",
    keywords: ["희망"],
  },
  {
    flower: "히아신스",
    symbol: "마음의 기쁨, 승리",
    image_url: "red",
    keywords: ["희망"],
  },
  {
    flower: "히아신스 (노란 히아신스)",
    symbol: "유희, 겸허한 사랑, 질투, 슬픔",
    image_url: "yellow",
    keywords: ["사랑", "슬픔"],
  },
  {
    flower: "히아신스 (자주 히아신스)",
    symbol: "미안해요",
    image_url: "purple",
    keywords: ["슬픔"],
  },
  {
    flower: "히아신스 (보라 히아신스)",
    symbol: "영원한 사랑",
    image_url: "purple",
    keywords: ["시간", "사랑"],
  },
  {
    flower: "히아신스 (푸른 히아신스)",
    symbol: "불변성",
    image_url: "blue",
    keywords: ["시간"],
  },
  {
    flower: "히어리",
    symbol: "봄의 노래",
    image_url: "red",
    keywords: ["자연", "문학"],
  },
  {
    flower: "후크시아",
    symbol: "선물, 열렬한 마음, 좋아함",
    image_url: "pink",
    keywords: ["희망", "사랑"],
  },
  {
    flower: "후리지아",
    symbol: "깨끗란 향기, 순결, 우정",
    image_url: "yellow",
    keywords: ["신체", "감각"],
  },
  {
    flower: "휴케라",
    symbol: "절실한 사랑",
    image_url: "blue",
    keywords: ["사랑"],
  },
  {
    flower: "훼닉스",
    symbol: "뜨거운 사랑",
    image_url: "purple",
    keywords: ["사랑"],
  },
]);
